### ISSUE TITLE
Dashboard UI is broken when clicking the reset button

### ISSUE THREAD

**Issue by PeterNgTr** [zalando/zalenium#1047]
## 🐛 Bug Report

After clicking the Reset button, the UI is broken. 
<img width="1078" alt="Screenshot 2019-09-10 at 10 46 04" src="https://user-images.githubusercontent.com/7845001/64598784-9d6b2a00-d3b8-11e9-8a35-4b30d481219d.png">

## To Reproduce

1. Navigate to http://localhost:4444/dashboard
2. Click Reset button

## Expected behavior

the UI loads perfectly.

**Comment by antlong** [comment]
@PeterNgTr I tried to reproduce on Chrome and it worked for me. Can you include the html of that page, so we can reproduce with your setup. Also what browser version and os version are you using?

**Comment by PeterNgTr** [comment]
Sorry, I just did try to reproduce this today but it loads normally. I guess maybe there is something is hidden I haven't found out yet. 😆

**Comment by xMutaGenx** [comment]
@PeterNgTr we're still getting this, I think it was something to do with the dashboard css not being copied over correctly

**Comment by PeterNgTr** [comment]
@xMutaGenx would be great if you could find a solid step to reproduce this. I haven't found out yet cause my laptop is a mix of many things like vpn connecting, sleeping over nights, etc.

**Comment by antlong** [comment]
Which browser, browser version, OS, OS version, etc.

**Comment by PeterNgTr** [comment]
I'm on MacOS 10.14.6, Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by antlong** [comment]
Built from current master?

**Comment by PeterNgTr** [comment]
yeah, I used the cmd from homepage

```
# Pull docker-selenium
    docker pull elgalu/selenium
    
    # Pull Zalenium
    docker pull dosel/zalenium
    
    # Run it!
    docker run --rm -ti --name zalenium -p 4444:4444 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/videos:/home/seluser/videos \
      --privileged dosel/zalenium start
```

**Comment by antlong** [comment]
Can you save the page as complete html, and attach it here. I will take a
look today.

**Comment by PeterNgTr** [comment]
oops, I just got the broken UI again. I also attached the complete html there.
[brokenui.txt](https://github.com/zalando/zalenium/files/3652006/brokenui.txt)

**Comment by xMutaGenx** [comment]
Ours runs in aws kubernetes, seems like the css,js etc for the dashboard is being loaded from the videos folder and the dashboard reset deletes everything apart from `dashboard.css` there. The files do get regenerated when a new video gets added though.

![Screenshot 2019-09-25 at 11 44 10](https://user-images.githubusercontent.com/35494061/65594443-b532d880-df8a-11e9-817a-e40877becec2.png)
You can see the files exist in the videos folder, then when the reset happens they get deleted, and regenerate when a new video is added.
![Screenshot 2019-09-25 at 11 44 59](https://user-images.githubusercontent.com/35494061/65594497-d4ca0100-df8a-11e9-9e44-c83c2c1d0e08.png)

**Comment by xMutaGenx** [comment]
Attached the complete HTML as well. Thanks for looking into it @antlong 

[Dashboard.txt](https://github.com/zalando/zalenium/files/3652036/Dashboard.txt)

**Comment by PeterNgTr** [comment]
Hi @antlong,

I tried the combined keys `CTRL+SHIFT+R` and seemed that is a solid step to reproduce this issue for me.

**Comment by dudziakm** [comment]
I've had the same today - after a few hours of working on my tests :(

**Comment by diemol** [comment]
Hi all,
Sadly we do not have enough time right now to work on this, a PR is much appreciated!

**Comment by diemol** [comment]
As mentioned in the previous comment, if someone has time to send a PR with this fix, we are happy to merge it. 
We are preparing the last Zalenium release, and afterwards the project will enter into a complete maintenance mode, which means that we will only reply to issues or answer questions in the chat, but no more code changes will be done.

**Comment by mookkiah** [comment]
Even though this project is not being developed, I see PR getting accepted for bug fixes. Appreciate that.

@diemol I would like to help fixing this bug.

Thinking of two different options

1. During cleanup instead of deleting entire videos directory, delete only the video (mp4) files, logs directory and update test information.

   Pros:
        - No value in deleting static web resources (dashboard.html, img, js) and copying it over again.
   Cons:
       - Making code change without the understanding of the original requirement. 
       -May be current code working well in non-docker environment – as this https://github.com/zalando/zalenium/issues/1047#issuecomment-530271473 says it is not reproducible
2. Add code to copy the css and img folder if not exists right after this line https://github.com/zalando/zalenium/blob/4b322387d0a88c6c81fec7466558df1e85fab98d/src/main/java/de/zalando/ep/zalenium/dashboard/Dashboard.java#L182
   Pros:
         - Will not break any existing functionality.
   Cons:
         - Due to this issue not reproducible, it could look like unwanted code for some other view point.

I found that the unit test code already there to for reset functionality. That gains confidence in fixing this issue. https://github.com/zalando/zalenium/blob/4b322387d0a88c6c81fec7466558df1e85fab98d/src/test/java/de/zalando/ep/zalenium/dashboard/DashboardCleanupServletTest.java#L44

Looked at TravisCI and found below error and still test considered as pass due to the finally block https://github.com/zalando/zalenium/blob/4b322387d0a88c6c81fec7466558df1e85fab98d/src/test/java/de/zalando/ep/zalenium/dashboard/DashboardCleanupServletTest.java#L52

```

[INFO] Running de.zalando.ep.zalenium.dashboard.DashboardCleanupServletTest
12:09:40.074 [http://localhost:40000] INFO  d.z.ep.zalenium.dashboard.Dashboard - Resetting Dashboard
12:09:40.101 [SauceLabs addTestToDashboard seleniumSessionId [RANDOM_EXTERNAL_KEY] testCompleted [false]] ERROR d.z.e.z.util.CommonProxyUtilities - java.io.FileNotFoundException: https://saucelabs.com/rest/v1/[secure]/jobs/RANDOM_EXTERNAL_KEY
java.io.FileNotFoundException: https://saucelabs.com/rest/v1/[secure]/jobs/RANDOM_EXTERNAL_KEY
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at de.zalando.ep.zalenium.util.CommonProxyUtilities.readJSONFromUrl(CommonProxyUtilities.java:53)
	at de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy.getTestInformation(SauceLabsRemoteProxy.java:107)
	at de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy$MockitoMock$292179025.getTestInformation$accessor$8xe8qm2K(Unknown Source)
	at de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy$MockitoMock$292179025$auxiliary$2yd5yATd.call(Unknown Source)
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:127)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:43)
	at org.mockito.Answers.answer(Answers.java:100)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:110)
	at de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy$MockitoMock$292179025.getTestInformation(Unknown Source)
	at de.zalando.ep.zalenium.proxy.CloudTestingRemoteProxy.lambda$0(CloudTestingRemoteProxy.java:272)
	at java.lang.Thread.run(Thread.java:748)
12:09:40.101 [SauceLabs addTestToDashboard seleniumSessionId [RANDOM_EXTERNAL_KEY] testCompleted [false]] INFO  d.z.e.z.util.CommonProxyUtilities - Trying download once again from https://saucelabs.com/rest/v1/[secure]/jobs/RANDOM_EXTERNAL_KEY
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.194 s - in
 
```
With this error, we cannot test the unit testing in Travis if I change the test method. Please advise how to proceed.

**Comment by mookkiah** [comment]
@diemol @elgalu @pearj Created [PR#1201](https://github.com/zalando/zalenium/pull/1201) by choosing option 2 as it will not break any functionality.
Travis CI build is failing because of missing keys to run test and Codacy. Please let me know if we have instruction for me to follow to get that passed.
