### ISSUE TITLE
Running on Azure AKS using ACI

### ISSUE THREAD

**Issue by jpaolini** [zalando/zalenium#1051]
## 🚀 Feature Proposal

Currently running Zalenium on Azure Kubernetes Services runs without issue.  When attempting to run the hub on the Azure Kubernetes Service and the nodes on the Azure Container Instance, the nodes send back the public IP of the pod instead of the internal network IP. Used [this](https://github.com/SeleniumHQ/docker-selenium/issues/946) as reference for the issue.
Attempted to set the environment variable `SELENIUM_NODE_HOST` to `__CONTAINER_IP__` or `{{CONTAINER_IP}}` so that the **elgalu/docker-selenium** image would dynamically set the host.  However, this doesn't work since the `SELENIUM_NODE_HOST` is hard coded to `0.0.0.0` in the `buildEnvVars` of `DockeredSeleniumStarter`.

The feature is to allow setting the `SELENIUM_NODE_HOST` as an environment variable for running on Kubernetes.

## Motivation

The motivation is so that we can leverage Azure Container Instance to easily scale nodes outside of the Azure Kubernetes Service clusters leveraging the resources.  This means we can operate for a lower cost with increased ability for parallel tests.

## Example

The motivation is the example of why and how it would be used.  This way the zalenium hub can run on the Azure Kubernetes Service then when the demand for tests increases it'll scaled the nodes out to the Azure Container Instance were we only pay for seconds of execution.  This means we can increase the parallelization without the need to pay for extra nodes in the cluster that would sit idle most of the time.

**Comment by diemol** [comment]
#1052 implements this, thank you @jpaolini!

**Comment by pipipo12** [comment]
Hi @jpaolini 
how can you config for zalenium run on aci
I can set taints and toleration and K8s schedules it to aci but it just restarted many time.
I tried exec to pod and run again [zalenium.sh start] the below error was raised
I think it related to this issue, right ?
Thanks in advance!

`Copying files for Dashboard...
Starting Nginx reverse proxy...
nginx: [emerg] bind() to 0.0.0.0:4444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:4444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:4444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:4444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:4444 failed (98: Address already in use)
nginx: [emerg] still could not bind()
Starting Selenium Hub...
.......16:09:42.972 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
.16:09:43.323 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
....16:09:44.436 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
..............................................16:09:54.583 [main] WARN  d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [wk-caas-a2ab1edc211a41819dfcb353cec5e51c-5370c0c8b5b1962e5b1161]  in namespace: [default]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:221)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177)
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:105)
        at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:49)
        at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:25)
        at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:68)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:97)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:83)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.openqa.grid.web.Hub.<init>(Hub.java:94)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
        at java.util.Optional.map(Optional.java:215)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:66)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:107)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:794)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:210)
        ... 18 common frames omitted
16:09:54.596 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - About to clean up any left over docker-selenium pods created by Zalenium
Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Error creating class with de.zalando.ep.zalenium.registry.ZaleniumRegistry : null
        at org.openqa.grid.web.Hub.<init>(Hub.java:99)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
        at java.util.Optional.map(Optional.java:215)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
Caused by: java.lang.ExceptionInInitializerError
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:97)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:83)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.openqa.grid.web.Hub.<init>(Hub.java:94)
        ... 5 more
Caused by: java.lang.NullPointerException
        at java.util.TreeMap.putAll(TreeMap.java:313)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:426)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:63)
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.deleteSeleniumPods(KubernetesContainerClient.java:504)
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.initialiseContainerEnvironment(KubernetesContainerClient.java:450)
        at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:52)
        at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:25)
        at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:68)
        ... 13 more`

**Comment by jpaolini** [comment]
@pipipo12, Below is the setup I did so that the hub runs on the k8s cluster and the nodes are created in the ACI.  Note, I wasn't able to move forward with it due to limitations with volume mounting.  It's been while since I dove into it, however if memory serves the issue was due to ACI's support for PVC.  I started going down the route of trying to use azure file storage, but didn't have time to investigate more.  

In the values.yaml
```
env:
    ZALENIUM_KUBERNETES_TOLERATIONS: "---\n- effect: \"NoSchedule\"\n  key: \"virtual-kubelet.io/provider\"\n  operator: \"Equal\"\n  value: \"azure\""
    ZALENIUM_KUBERNETES_NODE_SELECTOR: "type=virtual-kubelet"
    SELENIUM_NODE_HOST: "{{CONTAINER_IP}}"
    TIME_TO_WAIT_TO_START: 720000
```

`ZALENIUM_KUBERNETES_TOLERATIONS` is the tolerations for the nodes, setting the taints/tolerations in the values.yml is for the hub.  So my use case was to have the hub on k8s and then dynamically add nodes running on ACI as needed so it didn't overload the k8s cluster.

`TIME_TO_WAIT_TO_START` is needed since it'll take like 5 minutes to spin up the browser node on ACI, it takes a while to download the image and start it up.

very interested to see how far you're able to get.  we want to use the ACI, but it's been a bit troublesome for us.

**Comment by pipipo12** [comment]
Thanks @jpaolini . 
Agree that running zalenium on ACI is a great P/P approach for UI test.
About the trouble with volume, as I know PV/PVC is the drawback of aci at this time, the only way is to use azure file for pod run on ACI.
Let me try and hope that we can find a way to make it runnable
