### ISSUE TITLE
Zalenium containers not being created with Requests/Limits

### ISSUE THREAD

**Issue by ajcann** [zalando/zalenium#1061]
## 🐛 Bug Report

There might actually be two bugs here. In the helm chart we have defined:

    cpuRequest: 750m
    cpuLimit: 1000m
    memRequest: 1500Mi
    memLimit: 2Gi

Which comes across into the hub container as environment variables (these seem incorrect):

      ZALENIUM_KUBERNETES_CPU_REQUEST:     750m
      ZALENIUM_KUBERNETES_CPU_LIMIT:       2000m
      ZALENIUM_KUBERNETES_MEMORY_REQUEST:  1500Mi
      ZALENIUM_KUBERNETES_MEMORY_LIMIT:    1500Mi

But actual containers (nodes) created have no requests or limits defined at all.

I've also noticed that when the hub boots up I see
```
..11:51:36.291 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
...11:51:36.958 [main] WARN  d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support.
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:193)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:190)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.discoverContainerSecurityContext(KubernetesContainerClient.java:238)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:117)
	at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:49)
	at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:25)
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:66)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:97)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:83)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.openqa.grid.web.Hub.<init>(Hub.java:94)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
	at java.util.Optional.map(Optional.java:215)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
```

## Expected behavior

Zalenium containers should be created with memory and cpu request and limits defined

## Environment

OS: Kubernetes
Zalenium Image Version(s): dosel/zalenium:3
If using Kubernetes, specify your environment, and if relevant your manifests: GKE

**Comment by alfonso-presa** [comment]
@ajcann We are experimenting exactly the same behaviour on EKS... how did you solve it? Was it a problem on k8s?

**Comment by ajcann** [comment]
@alfonso-presa We were using a slightly dated helm chart with the latest docker image (3.141.59u). The latest version requires the podSecurityContext and containerSecurityContext keys to exists with at least a {} value. You may be using the :latest tag and not realize you need to have these values set. (Even if you're not using helm, I believe) https://github.com/zalando/zalenium/commit/750ef9af1c51f7c65800748ae09e4846422890ac

**Comment by alfonso-presa** [comment]
@ajcann Thank you. We noticed that after looking at another issue here :-). We did updated out helm and worked indeed. Thanks!
