### ISSUE TITLE
NullPointerExeption in Kubernetes

### ISSUE THREAD

**Issue by TobiX** [zalando/zalenium#1067]
## 🐛 Bug Report

It seems that the startup of Zalenium fails if for some reason the `securityContext` of the current container is `null`.

```
.07:03:30.986 [main] INFO d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
...07:03:31.671 [main] WARN d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support.
java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Objects.java:203)
at java.util.Optional.<init>(Optional.java:96)
at java.util.Optional.of(Optional.java:108)
at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:193)
at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:190)
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.discoverContainerSecurityContext(KubernetesContainerClient.java:238)
at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:117)
at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:49)
at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:25)
at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:66)
at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:97)
at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:83)
```

If I read the code correctly, this happens because the `securityContext` of the main Zalenium container is `null` (we did some experiments with linkerd, so that might have caused the issue) - `findFirst` tries to put `null` into an Optional and that isn't allowed (see also https://stackoverflow.com/questions/32466799/why-does-findfirst-throw-a-nullpointerexception-if-the-first-element-it-finds)

## To Reproduce

Sorry, not sure how to reproduce this...

## Expected behavior

Not throw an exception 😄 - This should probably be handled somehow. The easiest way I see is add another filter to the stream to check for this and set `configuredContainerSecurityContext` to null, but I don't know if that is the correct solution or of the startup should fail in that case (with some error message?)...

## Environment

OS: Linux
Zalenium Image Version(s): 3.141.59u

**Comment by brianvanstone** [comment]
Reproducing same when just using helm to install the chart from github

```
helm install --name my-grid                 \
    --set hub.serviceType=NodePort          \
    --set persistence.data.enabled=false    \
    --set persistence.video.enabled=false   \
    --set hub.videoRecordingEnabled=false   \
    --set hub.maxTestSessions=30            \
    --set hub.desiredContainers=6           \
    --set hub.maxDockerSeleniumContainers=6 \
    --set hub.debugEnabled=true             \
    --set hub.cpuLimit=500m                 \
    --set hub.memRequest=700Mi              \
    --set ingress.enabled=true              \
    --set ingress.path=/                    \
    --namespace my-namespace zalenium-github/zalenium
```

```
.17:16:48.447 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
...17:16:48.948 [main] WARN  d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support.
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203)
```

**Comment by diemol** [comment]
@TobiX @brianvanstone if this is still happening, could you please help us with a PR?

**Comment by Nilsty** [comment]
We ran into the same issue with our Zalenium setup.
Once we defined a security context in our deployment.yaml, the NullPointerExeption disappeared.
![image](https://user-images.githubusercontent.com/23235511/70636857-8ac1f480-1c36-11ea-93c8-9f0efb6b3213.png)

**Comment by brianvanstone** [comment]
@diemol @Nilsty I was similarly able to configure a security context to avoid the NullPointerExeption

**Comment by diemol** [comment]
Thank you @Nilsty for the important tip. If anyone wants to send a PR to add this to the docs, it would be welcomed. Or we can just leave it here, which also helps as documentation.

**Comment by dbwest** [comment]
I continue to get this error even after defining the security context.
