### ISSUE TITLE
java connect Exception: Connection Refused on starting Zalenium

### ISSUE THREAD

**Issue by msedhu1007** [zalando/zalenium#1120]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)
I am using Zalenium for running automation scripts.  I face java connect exception on starting docker. But Docker gets initiated  @after throwing the exception. On initiating the selenium scripts, I get same java.net.connect exception.

**Command used to start Docker in Linux :** sudo  docker run --rm -ti --name zalenium -p 4444:4444  -v /var/run/docker.sock:/var/run/docker.sock  --privileged dosel/zalenium start --debugEnabled true  --videoRecordingEnabled false --desiredContainers 1

**Docker version: 1.13.1
elgalu/selenium and dosel/zalenium : latest version**

**I get this exception on starting Docker.**
19:18:32.772 [AutoStartProxyPoolPoller] DEBUG d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_HVBUIi, containerId=0c2061f61861116632eef0046e67985c8962d5e0dccc8c151d3fd621c7ed033c, nodePort=40000].
19:18:32.832 [AutoStartProxyPoolPoller] DEBUG d.z.e.z.c.DockerContainerClient - Error while getting node status, probably the node is still starting up...
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.URL.openStream(URL.java:1057)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1153)
	at de.zalando.ep.zalenium.container.DockerContainerClient.isReady(DockerContainerClient.java:644)
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.containerHasStarted(DockeredSeleniumStarter.java:361)
	at de.zalando.ep.zalenium.proxy.AutoStartProxySet.checkContainers(AutoStartProxySet.java:392)
	at de.zalando.ep.zalenium.proxy.AutoStartProxySet.lambda$0(AutoStartProxySet.java:124)
	at java.lang.Thread.run(Thread.java:748)

**Comment by msedhu1007** [comment]
[dockerlogs.txt](https://github.com/zalando/zalenium/files/3957337/dockerlogs.txt)
[seleniumlogs.txt](https://github.com/zalando/zalenium/files/3957340/seleniumlogs.txt)
 
Please find Docker logs and Selenium execution logs. Both throw the same connection refused exception.

**Comment by diemol** [comment]
Yes, this is normal. You are running with `--debugEnabled true`, which just outputs everything, and one of those things is the health check of booting containers. The first health check can fail, but subsequent ones will work, that is why everything works afterwards.

**Comment by msedhu1007** [comment]
My Selenium scripts Fail as well with java.net.ConnectException: Connection refused (Connection refused). I hav attached those logs as well. I initiated my Selenium scripts only after the zalenium is up and running. I also cross checked to see "http://ip address:4444/grid/console" is up and running before initiating scripts. Automation scripts launch the chrome browser , opens the web page and fails(It fails in the first interaction with driver, driver.get method).
