### ISSUE TITLE
Empty pool of VM for setup Capabilities

### ISSUE THREAD

**Issue by PriyaMuthuvel** [zalando/zalenium#1170]
## Worked up to version:
![image](https://user-images.githubusercontent.com/23624668/77998640-01ead800-734f-11ea-942e-46d87321985f.png)

## To Reproduce

docker run --rm -ti --name zalenium2 -p 4444:4444  -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start

## Expected behavior

Testing should run

## Actual behavior

[10:38:28] I/launcher - Running 1 instances of WebDriver
[10:38:28] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[10:38:28] E/launcher - Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chromeOptions, chromeOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, count: 1, firefoxOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, marionette: true}
[10:38:28] E/launcher - WebDriverError: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chromeOptions, chromeOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, count: 1, firefoxOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, marionette: true}
    at Object.checkLegacyResponse (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at createDriver (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\index.js:635:14)
    at Hosted.getNewDriver (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\protractor\built\runner.js:195:43)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\protractor\built\runner.js:339:29
    at _fulfilled (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:834:54)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:796:13)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:556:49
[10:38:28] E/launcher - Process exited with error code 199

![image](https://user-images.githubusercontent.com/23624668/77998748-2fd01c80-734f-11ea-81cd-ac8e0acf44a8.png)

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10 Pro
Zalenium Image Version(s): latest
Docker version: 2.1.0.4(39773)
Docker-Compose version (if applicable): 1.24.1

![image](https://user-images.githubusercontent.com/23624668/77998936-7b82c600-734f-11ea-8327-9b0687e9fcbf.png)

**Comment by diemol** [comment]
I believe the **browserName** in the sent capabilities is wrong
```
{browserName: chromeOptions, chromeOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, count: 1, firefoxOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, marionette: true}
```
It should be **chrome**

**Comment by PriyaMuthuvel** [comment]
> I believe the **browserName** in the sent capabilities is wrong
> 
> ```
> {browserName: chromeOptions, chromeOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, count: 1, firefoxOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, marionette: true}
> ```
> 
> It should be **chrome**
Using chrome only
![image](https://user-images.githubusercontent.com/23624668/78004106-4a0df880-7357-11ea-90a8-19b72035899a.png)

**Comment by PriyaMuthuvel** [comment]
![image](https://user-images.githubusercontent.com/23624668/78004836-5181d180-7358-11ea-84f7-93f9e04b72b3.png)

![image](https://user-images.githubusercontent.com/23624668/78004879-5fcfed80-7358-11ea-8520-93b8ba8bb1d5.png)

**Comment by diemol** [comment]
Could you please paste the Zalenium logs from the beginning to the end? (No screenshots, but the text logs)

**Comment by PriyaMuthuvel** [comment]
C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation>yarn tags @reg
yarn run v1.19.1
$ rimraf reports/tmp/* && protractor built/config.js --cucumberOpts.tags @reg
[16:27:20] I/launcher - Running 1 instances of WebDriver
[16:27:20] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[16:27:20] E/launcher - Error forwarding the new session Empty pool of VM for setup Capabilities {args: [--disable-notifications, --no-sandbox], browserName: chrome, count: 1, w3c: false}
[16:27:20] E/launcher - WebDriverError: Error forwarding the new session Empty pool of VM for setup Capabilities {args: [--disable-notifications, --no-sandbox], browserName: chrome, count: 1, w3c: false}
    at Object.checkLegacyResponse (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\protractor\built\runner.js:195:43)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\protractor\built\runner.js:339:29
    at _fulfilled (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:834:54)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:796:13)
[16:27:20] E/launcher - Process exited with error code 199
error Command failed with exit code 199.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by PriyaMuthuvel** [comment]
C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation>docker run --rm -ti --name zalenium2 -p 4444:4444  -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start
Docker binary already present, will use that one.
Docker version 18.09.0, build 4d60db4
-- LOG 12:56:35:695287500 Ensuring docker works...
-- LOG 12:56:35:849355800 Ensuring docker-selenium is available...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
....12:56:38.089 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
.12:56:38.243 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
...12:56:38.890 [main] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium
......12:56:40.366 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
...12:56:41.233 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
.12:56:41.437 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
12:56:41.438 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.17.0.2:4445/grid/register/
12:56:41.441 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.17.0.2:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
CBT not enabled...
LambdaTest not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
12:56:56.928 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.3:40000
12:56:56.935 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.4:40001


![image](https://user-images.githubusercontent.com/23624668/78322749-3c41b880-758d-11ea-886c-57aaab78ed6f.png)

**Comment by diemol** [comment]
@PriyaMuthuvel the Zalenium log does not show anything, it only shows how it started successfully and nothing else. Why is that?

**Comment by PriyaMuthuvel** [comment]
Kindly look at the below error:

C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation>yarn tags @reg
yarn run v1.19.1
$ rimraf reports/tmp/* && protractor built/config.js --cucumberOpts.tags @reg
[16:27:20] I/launcher - Running 1 instances of WebDriver
[16:27:20] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[16:27:20] E/launcher - Error forwarding the new session Empty pool of VM for setup Capabilities {args: [--disable-notifications, --no-sandbox], browserName: chrome, count: 1, w3c: false}
[16:27:20] E/launcher - WebDriverError: Error forwarding the new session Empty pool of VM for setup Capabilities {args: [--disable-notifications, --no-sandbox], browserName: chrome, count: 1, w3c: false}
    at Object.checkLegacyResponse (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\protractor\built\runner.js:195:43)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\protractor\built\runner.js:339:29
    at _fulfilled (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:834:54)
    at C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\MSTSYS\Desktop\protractor\Website\mst-website-automation\node_modules\q\q.js:796:13)
[16:27:20] E/launcher - Process exited with error code 199
error Command failed with exit code 199.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by diemol** [comment]
Those are the protractor logs showing the error, we need to see the error in the Zalenium logs, which are not showing the request from protractor...
Are you sure tests are using Zalenium?

**Comment by PriyaMuthuvel** [comment]
@diemol , I Have followed the below steps for implementing the zalenium in my protractor test.

> docker pull elgalu/selenium
> docker pull dosel/zalenium
> docker run --rm -ti --name zalenium2 -p 4444:4444  -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start

Based on that, I can able to see the dashboard and live preview view. Kindly find it below:

# Live Preview View:
![image](https://user-images.githubusercontent.com/23624668/78376764-68405680-75ec-11ea-8747-e1ee5068cb3b.png)

# Dashboard view:
![image](https://user-images.githubusercontent.com/23624668/78376879-8c9c3300-75ec-11ea-932d-aaa1f34e3f3b.png)

And so I have received comments like Zalenium is ready.

#Zalenium Log:
![image](https://user-images.githubusercontent.com/23624668/78377052-c1a88580-75ec-11ea-82fc-d420409c8742.png)

So, I have tried to execute my protractor test that time I have received the below error,
![image](https://user-images.githubusercontent.com/23624668/78377256-06342100-75ed-11ea-9ee0-773d6abe596d.png)

#Config File:
`import * as path from 'path';
import { $, browser, Config, ExpectedConditions } from 'protractor';
import { Reporter } from './e2e/support/reporter';
import * as nodemailer from 'nodemailer';
import { url } from 'inspector';
const jsonReports = path.join(process.cwd(), '/reports/json');
var log4js = require('log4js');
export const config: Config = {
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    capabilities: {
        browserName: 'chrome',
        // version:'80.0',
        // marionette: true,
        w3c: false,
        //connTimeout:10,
        args: ['--disable-notifications', '--no-sandbox'], // add '--headless' to execute tests in headless mode
    
        // firefoxOptions: {
        //     w3c: false,
        //     args: ['--disable-notifications', '--no-sandbox'], // add '--headless' to execute tests in headless mode
        // },
        // chromeOptions: {
        //     w3c: false,
        //     //connTimeout:10,
        //     args: ['--disable-notifications', '--no-sandbox'], // add '--headless' to execute tests in headless mode
        // },
    },
    specs: [
        '../e2e/features/**/*.feature',
    ],
    cucumberOpts: {
        format: [
          `json:${jsonReports}/report.json`,
       './built/e2e/support/allure-reporter.js',
    ],
        require: [
            path.resolve(process.cwd(), './built/e2e/steps/**/*.js'),
            path.resolve(process.cwd(), './built/e2e/support/**/*.js'),
            
        ],
        strict: true,
        tags: '@smoke',
    },
    onComplete: () => {
    browser.manage().timeouts().pageLoadTimeout(40000);
+   browser.manage().timeouts().implicitlyWait(5000);
browser.sleep(120000);
        Reporter.createHTMLReport();
       
    },
    beforeLaunch: async () => {
        log4js.configure({
            appenders: [
                { type: 'log4js-protractor-appender', category: 'protractorLog4js' },
                {
                    type: "file",
                    filename: './logs/ExecutionLog.log',
                    category: 'protractorLog4js'
                }
            ]
        });
    },
    onPrepare: async () => {
        browser.logger = log4js.getLogger('protractorLog4js');
        browser.manage().timeouts().pageLoadTimeout(40000);
+         browser.manage().timeouts().implicitlyWait(5000);
        Reporter.createDirectory(jsonReports);
        await browser.waitForAngularEnabled(false);
        await browser.manage().window().maximize();
        await browser.get(browser.baseUrl,40000);
        await browser.sleep(5000);
    },
    
    baseUrl: 'https://www.google.com/',
    directConnect: false,
    seleniumAddress: 'http://localhost:4444/wd/hub',
    // You could set no globals to true to avoid jQuery '$' and protractor '$'
    // collisions on the global namespace.
    noGlobals: true
};
`

**Comment by diemol** [comment]
Are you sure protractor is not starting its own Selenium Server? If the request had reached out to Zalenium, you'd see more things in the log output.

**Comment by PriyaMuthuvel** [comment]
Yes, Protractor is not starting its server

**Comment by diemol** [comment]
Then please attach the Zalenium log where one can see the incoming requests

**Comment by PriyaMuthuvel** [comment]
19:00:07] E/launcher - Error forwarding the new session cannot find : Capabilities {browserName: chrome, chromeOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, count: 1, firefoxOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, marionette: true, version: 80.0}
[19:00:07] E/launcher - WebDriverError: Error forwarding the new session cannot find : Capabilities {browserName: chrome, chromeOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, count: 1, firefoxOptions: {args: [--disable-notifications, --no-sandbox], w3c: false}, marionette: true, version: 80.0}
    at Object.checkLegacyResponse (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/selenium-webdriver/index.js:626:16)
    at Hosted.getNewDriver (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/protractor/built/runner.js:195:43)
    at /home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/protractor/node_modules/q/q.js:834:54)
    at /home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/centos/MST_Projects/Demo_Jobs/Automation_Docker/node_modules/protractor/node_modules/q/q.js:796:13)
[19:00:07] E/launcher - Process exited with error code 199
error Command failed with exit code 199.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Build step 'Execute shell' marked build as failure

**Comment by diemol** [comment]
@PriyaMuthuvel sorry, those logs are not coming out from Zalenium... Please double-check the incoming requests to Zalenium through its logs.

**Comment by PriyaMuthuvel** [comment]
@diemol The issue has been fixed. 
I have followed the below steps for fixing the issues.

- Kill the port and follow the zalenium commend
- And then added the below two lines before the capabilities
          **SELENIUM_PROMISE_MANAGER: false,
              ignoreUncaughtExceptions: true,**
![image](https://user-images.githubusercontent.com/23624668/78781237-7eb82a80-79bd-11ea-995c-2daab6df5c1c.png)
