### ISSUE TITLE
Zalenium Browserstack UnknownHostException: api.browserstack.com error

### ISSUE THREAD

**Issue by semihural** [zalando/zalenium#1189]
## 🐛 Bug Report

We have a zalenium set up running in kubernetes and we would like to integrate with Browserstack. The issues are,

1. When we did not set any http_proxy and https_proxy for zalenium (dosel/zalenium) everythings works properly even if we set a proxy for (elgalu/selenium). But when I set a env variables like as below zalenium is not running properly.

 env:
    http_proxy: http://<proxy>:port
    https_proxy: http://<proxy>:port

Here is the log when I set a proxy for zalenium.

```
zalenium-6b5965b454-mlr52                       1/1     Running   0          15s
capel0068340585:~ semural$ kubectl logs zalenium-6b5965b454-mlr52 -n monitoring
Kubernetes service account found.
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
...10:57:09.997 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
10:57:10.062 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.10:57:10.325 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
10:57:10.370 [main] WARN  d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [zalenium-6b5965b454-mlr52]  in namespace: [monitoring]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
```

2. When we did not set a proxy zalenium runs properly, but this time when we enable browserstack we could not able to connect to browserstack.

So how should we set the proxy env vars for both of images to run everything properly include connecting browserstack?

here is output of kubectl logs zalenium-6b7d5df9cb-m6p6x -n monitoring
```
Starting Browser Stack node...
..08:58:04.746 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
.08:58:04.812 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching a Selenium Grid node on port 30002
08:58:05.015 [main] INFO  global - Initialising WebDriverServlet
.08:58:05.069 [main] INFO  o.o.s.remote.server.SeleniumServer - Selenium Server is up and running on port 30002
08:58:05.069 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium Grid node is up and ready to register to the hub
.08:58:05.347 [main] INFO  o.o.g.i.utils.SelfRegisteringRemote - Registering the node to the hub: http://localhost:4444/grid/register
08:58:05.422 [BrowserStack] ERROR d.z.e.z.util.CommonProxyUtilities - java.net.UnknownHostException: api.browserstack.com
java.net.UnknownHostException: api.browserstack.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)<!--
Please be sure to include an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/ at java.lang.Thread.run(Thread.java:748)
09:11:06.656 [BrowserStack] INFO  d.z.e.z.util.CommonProxyUtilities - Trying download once again from https://api.browserstack.com/automate/plan.json
.................09:11:10.261 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://10.6.5.55:40000
.09:11:10.533 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://10.6.10.103:40000
.....09:11:11.656 [BrowserStack] ERROR d.z.e.z.util.CommonProxyUtilities - java.net.UnknownHostException: api.browserstack.com
```
-->

## Expected behavior

Connecting to browser stack behind of proxy to run tests.

## Environment

OS: 
Zalenium Image Version(s): latest
Kubernetes Version : v.17

```
NAME                                            READY   STATUS             RESTARTS   AGE
zalenium-40000-fwg85                            1/1     Running            0          2m4s
zalenium-40000-j2cz8                            1/1     Running            0          2m4s
zalenium-6b7d5df9cb-m6p6x                       0/1     CrashLoopBackOff   7          17m
```

**Comment by semihural** [comment]
I fixed the issue via adding proxy using _JAVA_OPTS variable.
