### ISSUE TITLE
java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by iMbaundso** [zalando/zalenium#172]
Setting --maxDockerSeleniumContainers 4 does not wirk in version 3.3.1l. It looks like zalenium is not able to figure out if the containers have started up successfully due to the connection refused exception and then happily continues creating new containers as it looks like 0 are running. Tried using the compose file https://github.com/zalando/zalenium/blob/master/docs/docker/docker-compose.yaml

```10:17:10.900 DEBUG - Error while getting node status.
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.URL.openStream(URL.java:1045)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:1153)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.checkContainerStatus(DockerSeleniumStarterRemoteProxy.java:481)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:455)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:428)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.lambda$getNewSession$2(DockerSeleniumStarterRemoteProxy.java:386)
        at java.lang.Thread.run(Thread.java:748)```

**Comment by diemol** [comment]
Just merged #174 to master to fix this, will release this in a couple of days. Thanks again for reporting @iMbaundso!

**Comment by iMbaundso** [comment]
Thank you so much @diemol. Will give it a try then :)

**Comment by diemol** [comment]
Hi @iMbaundso,

We just released https://github.com/zalando/zalenium/releases/tag/3.3.1m, so please give it a try.

I'll close this issue now but feel free to reopen if a related issue comes up.
