### ISSUE TITLE
Connection refused to containers after a few mins

### ISSUE THREAD

**Issue by RossFMR** [zalando/zalenium#210]
I'm running Ubuntu 14.4 on a 6 core 32Gb VM.  It starts working great but after a few mins none of the containers are reachable and I'm getting null pointer errors. I am starting it with this:
sudo docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /videos:/home/seluser/videos \
    --privileged dosel/zalenium start --maxDockerSeleniumContainers 6 --screenWidth 1440 --screenHeight 810 --timeZone "America/Montreal" --videoRecordingEnabled true

This is the log:
15:47:36.998 INFO - Trying to create a new session on test slot {firefox_binary=/home/seluser/firefox-for-sel-3/firefox, seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1440x810, tz=America/Montreal, browserName=firefox, maxInstances=1, screenResolution=1440x810, resolution=1440x810, version=52.0.2, platform=LINUX}
15:47:37.600 INFO - [DS] Container zalenium_40046 is up after ~4 seconds...
15:47:39.379 INFO - http://172.17.0.6:40046 [bash, -c, start-video]
15:47:39.801 ERROR - cannot forward the request Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:372)
	at org.openqa.grid.internal.TestSession.forward(TestSession.java:227)
	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardRequest(RequestHandler.java:94)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:127)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
15:47:39.802 INFO - http://172.17.0.6:40046 AFTER_SESSION command received. Node should shutdown soon...
15:47:39.806 INFO - http://172.17.0.6:40046 [bash, -c, stop-video]
15:47:39.943 INFO - http://172.17.0.6:40046 Video file copied to: /home/seluser/videos/zalenium_00d66c96-8d31-4d36-950b-a7fc08554c48_firefox_LINUX_20170816154739.mkv
15:47:40.322 ERROR - Error running afterSession for ext. key ef9252ee-1ff3-44bd-92b9-971dd4111132, the test slot is now dead: Container 99236c2e3e487e06835cbe88c06c0120e4cfd5c041a45b0d70131526dc96ca58 is not running.
java.lang.IllegalStateException: Container 99236c2e3e487e06835cbe88c06c0120e4cfd5c041a45b0d70131526dc96ca58 is not running.

Any idea on the stability issues?

**Comment by diemol** [comment]
Hi @RossFMR,

We are not aware of these issues. Is this still happening?

How many tests are you running in parallel? Perhaps it is something related to some specific conditions.

**Comment by RossFMR** [comment]
around 5-8 per min.  Some tests can be very long.  I limited the amount with --maxDockerSeleniumContainers 6  but it doesn't matter how I change the max, it still happens after the same amount of time.

**Comment by diemol** [comment]
@RossFMR 
we upgraded to Selenium 3.5.3, and improved several things. Perhaps this is now solved for you, can you please check again?

**Comment by diemol** [comment]
I'll close this one due to inactivity, feel free to reopen in case the issue is still present.
