### ISSUE TITLE
Unable to connect to saucelabs

### ISSUE THREAD

**Issue by srinuuk** [zalando/zalenium#230]
When trying to start Zalenium with sauce lab enable getting below error
SauceLabsRemoteProxy failed to start after 40 seconds, failing..

Set with valid Saucelabs username and key. I am trying to start zalenium on mac.

**Comment by diemol** [comment]
Can you share your the docker command you are using please?

**Comment by srinuuk** [comment]
docker run --rm -ti --name zalenium -p 4444:4444   -e DOCKER=1.11     -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY     -v /tmp/videos:/home/seluser/videos     -v /var/run/docker.sock:/var/run/docker.sock     --privileged dosel/zalenium start --sauceLabsEnabled true

I have set credentials in bash profile exporting SAUCE_USERNAME and SAUCE_ACCESS_KEY.
First I tried on AWS redhat got the same error then I tried on Mac and I got the same error.
I have also tried to use mac sauce connector on mac updating script as below and rebuilding the image. 
# ------------------------#
# Sauce Connect Tunneling #
# ------------------------#
# https://docs.saucelabs.com/reference/sauce-connect/
# Layer size: medium: ~13 MB
ENV SAUCE_CONN_VER="sc-4.4.9-osx" \
    SAUCE_CONN_DOWN_URL="https://saucelabs.com/downloads"
RUN cd /tmp \
  && wget -nv "${SAUCE_CONN_DOWN_URL}/${SAUCE_CONN_VER}.zip" \
  && unzip "${SAUCE_CONN_VER}.zip" \
  && rm -rf /usr/local/${SAUCE_CONN_VER} \
  && mv ${SAUCE_CONN_VER} /usr/local \
  && rm "${SAUCE_CONN_VER}.zip" \
  && ln -sf /usr/local/${SAUCE_CONN_VER}/bin/sc /usr/local/bin/sc \
  && which sc

**Comment by srinuuk** [comment]
Any thoughts on above issue? Also, have another question. Is there anyway to create sauce tunnel by passing additional Sauce tunnel arguments?

**Comment by diemol** [comment]
I haven't had time to check it. But I am missing some data:
- How are you exporting the env vars for Sauce Labs? Did you follow the [example](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#with-sauce-labs-enabled)?
- You don't need to add the sauce connect file, it is already there.
- What parameters do you need?

**Comment by srinuuk** [comment]
Yes, I followed Saucelabs example.
Right we don't need sauce connect file.
Need parameters to set proxy for sauce connector. I am fine, I have set in 'start-saucelabs.sh' file.

I have increased timeout from default 40 sec to higher number and I see it's timing out when trying to make rest call 'https://saucelabs.com/rest/v1/users/'
Below is the trace:

java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at de.zalando.ep.zalenium.util.CommonProxyUtilities.readJSONFromUrl(CommonProxyUtilities.java:43)
	at de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy.updateSLCapabilities(SauceLabsRemoteProxy.java:35)
	at de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy.<init>(SauceLabsRemoteProxy.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:369)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:104)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
16:03:43.092 INFO - Trying download once again from https://saucelabs.com/rest/v1/users/*****
____________________

I have tried updating with my internal proxy in zalenium.sh file 
export http_proxy= <Internal proxy>
export https_proxy= <Internal proxy>

Also tried to set proxy as bellow:
java -Dhttp.proxyHost=<hostname> -Dhttp.proxyPort=<port> -Dhttp.proxyUser=<Username> -Dhttps.proxyPassword=<password> -Djava.util.logging.config.file=logging_${DEBUG_MODE}.properties \
         -jar ${SELENIUM_ARTIFACT} -role node -hub http://localhost:4444/grid/register \
         -registerCycle 0 -proxy de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy \
         -nodePolling 90000 -port 30001 -debug ${DEBUG_ENABLED} &

But still i get same timeout error :-(

Please let me know if you have any other suggestions.

**Comment by srinuuk** [comment]
Even if I set proxy in docker file looks like it's not taking when 'zalenium.sh' is running with sudo. 
exec sudo --preserve-env ./zalenium.sh "$@".

Any suggestions?

**Comment by srinuuk** [comment]
After more digging and R&D finally I made changes to CommonProxyUtilities.java file setting proxy and it worked. Now I am able to see saucelabs node connected to GRID and connection established. But unfortunately getting another problem. Other Chrome and Firefox nodes not coming up if I enable Saucelabs. :-( If i do not enable saucelabs Chrome and Firefox nodes coming up perfectly fine. 

Here is the error I get when I enable saucelabs. I see this error for Chrome and Firefox. Not for suacelabs.

22:51:55.292 [qtp919112242-28] WARN  o.s.jetty9.server.HttpChannel - /grid/register
java.security.InvalidParameterException: Error: Host name may not be null

**Comment by srinuuk** [comment]
Closing this issue since original issue connecting to saucelabs is resolved. I will open another issue for selenium Chrome and Firefox containers.

**Comment by clyton** [comment]
@diemol can you please fix this issue. I am getting the same problem as listed above. I am following your example. But I have also added the zalenium_http_proxy variables :

  export SAUCE_USERNAME=<your Sauce Labs username>
    export SAUCE_ACCESS_KEY=<your Sauce Labs access key>
    docker run --rm -ti --name zalenium -p 4444:4444 \
      -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY \
      -v /tmp/videos:/home/seluser/videos \
      -v /var/run/docker.sock:/var/run/docker.sock \
-e "zalenium_http_proxy=<my-company-proxy>"
-e "zalenium_https_proxy=<my-company-proxy>"
-e "zalenium_no_proxy=172.16/12, 10.0.0.0/8, *.local, 169.254/16, 192.168.99.*, localhost, 127.0.0.1" \ 
      --privileged dosel/zalenium start --sauceLabsEnabled true

With the above command I get unknown host exception for saucelabs.com

I then added the -e https_proxy  http_proxy and I get error on connecting to local host
