### ISSUE TITLE
Error When Calling inspectContainer from DockerContainerClient#getZaleniumNetwork

### ISSUE THREAD

**Issue by ReservedDeveloper** [zalando/zalenium#232]
I've recently encountered an error spinning up Zalenium (following #199). It seems to occur during the startup of the node containers. Error message is as follows 
```
DockerSeleniumStarter node started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
21:16:47.585 DEBUG - Env. variable BUILD_URL value is not set, falling back to default: 
21:16:47.618 DEBUG - Env. variable BUILD_URL value is not set, falling back to default: 
Exception in thread "Thread-11" java.lang.NullPointerException: path is 'null'.
	at jersey.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
	at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:59)
	at com.spotify.docker.client.DefaultDockerClient.inspectContainer(DefaultDockerClient.java:976)
	at de.zalando.ep.zalenium.container.DockerContainerClient.getZaleniumNetwork(DockerContainerClient.java:342)
	at de.zalando.ep.zalenium.container.DockerContainerClient.createContainer(DockerContainerClient.java:197)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:428)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.lambda$createContainersOnStartup$6(DockerSeleniumStarterRemoteProxy.java:541)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-10" java.lang.NullPointerException: path is 'null'.
	at jersey.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
	at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:59)
	at com.spotify.docker.client.DefaultDockerClient.inspectContainer(DefaultDockerClient.java:976)
	at de.zalando.ep.zalenium.container.DockerContainerClient.getZaleniumNetwork(DockerContainerClient.java:342)
	at de.zalando.ep.zalenium.container.DockerContainerClient.createContainer(DockerContainerClient.java:197)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:428)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.lambda$createContainersOnStartup$5(DockerSeleniumStarterRemoteProxy.java:531)
	at java.lang.Thread.run(Thread.java:748)
21:18:16.617 DEBUG - Handling: GET /status
21:18:16.617 DEBUG - Executing: org.openqa.selenium.remote.server.handler.Status@34b28cf2)
21:18:16.617 DEBUG - Done: org.openqa.selenium.remote.server.handler.Status@34b28cf2
21:18:16.617 DEBUG - Finished: GET /status
21:19:46.641 DEBUG - Handling: GET /status
21:19:46.641 DEBUG - Executing: org.openqa.selenium.remote.server.handler.Status@4f01fcba)
21:19:46.641 DEBUG - Done: org.openqa.selenium.remote.server.handler.Status@4f01fcba
21:19:46.641 DEBUG - Finished: GET /status
[...]
```

I've checked the hub container, and docker is present, and the zalenium container shows on a `docker ps` call.

Short of adding some additional trace logging around that section, I'm at a loss. Any insights would be appreciated!

**Comment by diemol** [comment]
Hi @ReservedDeveloper,

How do you start Zalenium? (docker command)

The error happens when Zalenium is trying to figure out the network where it is running, so the new containers are also in that network. Somehow, it cannot find it... I hope I can understand why based on the command you use to start it.

**Comment by ReservedDeveloper** [comment]
The command I'm calling is:

```
docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $(pwd)/videos:/home/seluser/videos \
    -v $(pwd)/certPath:/home/seluser/.pki/nssdb
    -v $(pwd)/policies/managed:/etc/opt/chrome/policies/managed
    --privileged my.local.registry:5000/dosel/zalenium start \
    --seleniumImageName my.local.registry:5000/elgalu/selenium --debugEnabled true
```

This seems to work fine on my local machine. But on the remote server it's being run on, it's encountering issues. However, when I check (via `docker ps`) after the run, I'm able to see the main zalenium container up and running.

**Comment by diemol** [comment]
Could you please do:
`docker network ls`
and 
`docker inspect {zaleniumContainerName}`
in the server where you find the issues?

**Comment by gilles-stragier** [comment]
I'm encountering the exact same issue, using the default start command

```
  docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    --privileged dosel/zalenium start
``` 

docker ls network
```
[ban@s00sv170 ~]$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
0081f6f47864        bridge              bridge              local               
1b96045eadee        host                host                local               
e1341f8a1321        none                null                local      
```

docker inspect zalenium
```
[
    {
        "Id": "38beecb2b6217f1aceeff7ab1fe1a4491872fe601f699853b86780f6b1e2f432",
        "Created": "2017-10-06T11:25:17.803298675Z",
        "Path": "entry.sh",
        "Args": [
            "start"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 18256,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-10-06T11:25:18.187655475Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:127df739e6a651d4a518215fb68aa40330da2ed4a7bc8674abbdb7c4381469c5",
        "ResolvConfPath": "/var/data/docker/containers/38beecb2b6217f1aceeff7ab1fe1a4491872fe601f699853b86780f6b1e2f432/resolv.conf",
        "HostnamePath": "/var/data/docker/containers/38beecb2b6217f1aceeff7ab1fe1a4491872fe601f699853b86780f6b1e2f432/hostname",
        "HostsPath": "/var/data/docker/containers/38beecb2b6217f1aceeff7ab1fe1a4491872fe601f699853b86780f6b1e2f432/hosts",
        "LogPath": "/var/data/docker/containers/38beecb2b6217f1aceeff7ab1fe1a4491872fe601f699853b86780f6b1e2f432/38beecb2b6217f1aceeff7ab1fe1a4491872fe601f699853b86780f6b1e2f432-json.log",
        "Name": "/zalenium",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/run/docker.sock:/var/run/docker.sock",
                "/tmp/videos:/home/seluser/videos"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "4444/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "4444"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "docker-runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "365",
                "DeviceName": "docker-253:4-201326728-f24bcc59ad2a2e0023c0def39978f36f318812f314f902be23af16fae6276c64",
                "DeviceSize": "10737418240"
            }
        },
        "Mounts": [
            {
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/tmp/videos",
                "Destination": "/home/seluser/videos",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "38beecb2b621",
            "Domainname": "",
            "User": "seluser",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "4444/tcp": {},
                "4445/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "UBUNTU_FLAVOR=xenial",
                "UBUNTU_DATE=20170915",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBCONF_NONINTERACTIVE_SEEN=true",
                "LANG_WHICH=en",
                "LANG_WHERE=US",
                "ENCODING=UTF-8",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "TZ=Europe/Berlin",
                "DOCKER_HOST=unix:///var/run/docker.sock",
                "DOCKER_BUCKET=download.docker.com",
                "DOCKER=17.06.2-ce",
                "SAUCE_CONN_VER=sc-4.4.9-linux",
                "SAUCE_CONN_DOWN_URL=https://saucelabs.com/downloads",
                "BSTACK_TUNNEL_URL=https://www.browserstack.com/browserstack-local",
                "BSTACK_TUNNEL_ZIP=BrowserStackLocal-linux-x64.zip",
                "TB_TUNNEL_URL=https://testingbot.com/tunnel/testingbot-tunnel.jar",
                "SEL_MAJOR_VER=3.6",
                "SEL_PATCH_LEVEL_VER=0",
                "SEL_VER=3.6.0",
                "ZAL_VER=zalenium-3.6.0a",
                "BROWSER_STACK_TUNNEL_OPTS=-skipCheck -v -forcelocal",
                "BROWSER_STACK_TUNNEL_ID=zalenium",
                "BROWSER_STACK_TUNNEL=false",
                "BROWSER_STACK_WAIT_TIMEOUT=2m",
                "SAUCE_TUNNEL_MAX_RETRY_ATTEMPTS=1",
                "SAUCE_TUNNEL_READY_FILE=/tmp/sauce-connect-ready",
                "SAUCE_TUNNEL_ID=zalenium",
                "SAUCE_TUNNEL_DOCTOR_TEST=false",
                "SAUCE_WAIT_TIMEOUT=2m",
                "SAUCE_TUNNEL=false",
                "TESTINGBOT_TUNNEL_OPTS=--se-port 4447",
                "TESTINGBOT_TUNNEL=false",
                "TESTINGBOT_WAIT_TIMEOUT=2m"
            ],
            "Cmd": [
                "start"
            ],
            "Image": "dosel/zalenium",
            "Volumes": null,
            "WorkingDir": "/home/seluser",
            "Entrypoint": [
                "entry.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Team EP \u003cdiemol+team-ep@gmail.com\u003e"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "5377990c5ea5da2c622edf8ae99c27ad72ffa3fdf975313dee0891c1a06c770c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ],
                "4445/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/5377990c5ea5",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "9036697965e43499700c1de71c781ff4f485c80c11b9c799cffedc6326ed0e45",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "0081f6f47864ef06c32630ab1ab76516cf363bdb213b473abcd42846c0ae3bb3",
                    "EndpointID": "9036697965e43499700c1de71c781ff4f485c80c11b9c799cffedc6326ed0e45",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]
```

Having looked at the code, the problem might be that he doesn't find the container id, thus the call to inspect fails (as containerId is null). Just didn't figure why yet

**Comment by diemol** [comment]
@ReservedDeveloper @gilles-stragier are you running Zalenium in Fedora?

Could it be the same as #276?

**Comment by gilles-stragier** [comment]
We're running on Red Hat Enterprise Linux Atomic Host. So not that far from Fedora I guess ...

It seems the exact same symptom (containerId is null).

But the command given as the root case seems to work a bit differently. The containers themselves don't seem to be located in /proc/self/cgroup.

```
[bash ~]$ grep docker /proc/self/cgroup
[bash ~]$
```
so if the containerId comes from that file, it might never find anything.

**Comment by ReservedDeveloper** [comment]
Pretty much the same as @gilles-stragier . Slightly different version of Red Hat, but same issue with contents in `/proc/self/cgroup`.

**Comment by gilles-stragier** [comment]
Might have talked a little bit too fast, sorry :)

From inside a container, then it's exactly the same as in issue #276

```
seluser@df5583a7e549:/$ grep docker /proc/self/cgroup
11:blkio:/system.slice/docker-df5583a7e549f5609410ab1fd8e64713a6b3b8431ce7383545c9c7c0de153d1a.scope
...
```

So the fix should do it, thanks

**Comment by diemol** [comment]
Well, we released https://github.com/zalando/zalenium/releases/tag/3.6.0c which should work for current known environments plus Fedora.

I guess we need to execute the current command, and if it does not return something, execute the proper one for Red Hat.

@ReservedDeveloper @gilles-stragier do you guys feel like giving it a try? I don't have any Red Hat to try it. Would be cool if you can give us a hand.

**Comment by diemol** [comment]
Ah ok, so maybe it works in the end, I was typing the previous comment and I didn't see yours before @gilles-stragier

Then please give it a try and let us know :)

**Comment by ReservedDeveloper** [comment]
I just pulled the latest and was able to run without encountering this issue. Thanks for digging in @diemol. Feel free to close out once @gilles-stragier reports in.

**Comment by jkandasa** [comment]
@ReservedDeveloper @gilles-stragier @diemol Red Hat Enterprise Linux is a downstream of Fedora :)

**Comment by diemol** [comment]
Thanks to @jkandasa for digging into it! :)

**Comment by gilles-stragier** [comment]
Sorry for the delay. I confirm everything works without problems ! thanks a lot to all of you

**Comment by diemol** [comment]
Nice, thanks for reporting back.
