### ISSUE TITLE
Not able to start Chrome & Firefox containers with Zalenium when saucelabs enabled

### ISSUE THREAD

**Issue by srinuuk** [zalando/zalenium#253]
When I start Zalenium with Saucelabs enabled I am getting below error, Selenium containers for firefox and chrome are not getting started. When I run without saucelabs enabled Chrome and Firefox containers are up without any issues. Any thoughts why we get 'Home name' may not be null error? .Some conflict is there with SauceLabs node and elgalu/docker-selenium containers.
Could you please suggest?
Note: I am using latest zalando/zalenium and  elgalu/docker-selenium

```
15:39:41.162 [qtp2041605291-15] WARN o.s.jetty9.server.HttpChannel - /grid/register
java.security.InvalidParameterException: Error: Host name may not be null
at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:357)
at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:103)
at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:70)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by srinuuk** [comment]
Here is complete command:
docker run --rm -ti --name zalenium -p 4444:4444 -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY -v /tmp/videos:/home/seluser/videos -v /var/run/docker.sock:/var/run/docker.sock --privileged efe1c0dcbe15 start --sendAnonymousUsageInfo false --seleniumImageName d0b50b81dda6 --sauceLabsEnabled true

If I remove --sauceLabsEnabled true parameter. Chrome and Firefox nodes are up without any issues. Please let me know if you are looking for more details. Thank you for your quick response on this.

Note: For both Zalenium and selenium docker images I have added our internal proxy and rebuilt. So, you do not see the actual name of the docker images.

Here is the complete log:
Docker binary already present, will use that one.
Docker version 17.03.0-ce, build 60ccb22
-- LOG 16:28:23:718091001 Ensuring docker works...
-- LOG 16:28:23:749868040 Ensuring no stale Zalenium related containers are still around...
-- LOG 16:28:23:767096020 Ensuring docker-selenium is available...
-- LOG 16:28:24:293703408 Running additional checks...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
..16:28:25.044 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
16:28:25.046 INFO - Launching Selenium Grid hub
..16:28:25.584 INFO - binding de.zalando.ep.zalenium.servlet.LivePreviewServlet to /grid/admin/LivePreviewServlet/*
16:28:25.585 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumConsoleServlet to /grid/admin/ZaleniumConsoleServlet/*
16:28:25.586 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumResourceServlet to /grid/admin/ZaleniumResourceServlet/*
16:28:25.587 INFO - binding de.zalando.ep.zalenium.dashboard.DashboardCleanupServlet to /grid/admin/DashboardCleanupServlet/*
.16:28:25.744 INFO - Will listen on 4445
16:28:25.834 INFO - Nodes should register to http://172.17.0.2:4445/grid/register/
16:28:25.835 INFO - Selenium Grid hub is up and running
Selenium Hub started!
Starting DockerSeleniumStarter node...
..16:28:26.244 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
16:28:26.246 INFO - Launching a Selenium Grid node
.2017-09-21 16:28:26.616:INFO::main: Logging initialized @598ms to org.seleniumhq.jetty9.util.log.StdErrLog
16:28:26.661 INFO - Driver class not found: com.opera.core.systems.OperaDriver
.16:28:26.693 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
16:28:26.696 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
16:28:26.698 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
16:28:26.721 INFO - Using the passthrough mode handler
2017-09-21 16:28:26.747:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-09-21 16:28:26.770:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@2e005c4b{/,null,STARTING} has uncovered http methods for path: /
2017-09-21 16:28:26.774:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@2e005c4b{/,null,AVAILABLE}
2017-09-21 16:28:26.785:INFO:osjs.AbstractConnector:main: Started ServerConnector@10e31a9a{HTTP/1.1,[http/1.1]}{0.0.0.0:30000}
2017-09-21 16:28:26.786:INFO:osjs.Server:main: Started @768ms
16:28:26.786 INFO - Selenium Grid node is up and ready to register to the hub
16:28:26.798 INFO - Registering the node to the hub: http://localhost:4444/grid/register
......16:28:28.133 ERROR - [DS]  A downloaded docker-selenium image was not found!
16:28:28.219 INFO - [DS] Capabilities grabbed from the docker-selenium image
16:28:28.224 INFO - Registered a node http://172.17.0.2:30000
16:28:28.224 INFO - The node is registered to the hub and ready to use
16:28:28.228 INFO - [DS]  Setting up 2 nodes...
16:28:28.230 INFO - 2 containers were created, it will take a bit more until all get registered.
DockerSeleniumStarter node started!
Starting Sauce Labs node...
..16:28:28.570 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
16:28:28.572 INFO - Launching a Selenium Grid node
.2017-09-21 16:28:28.907:INFO::main: Logging initialized @567ms to org.seleniumhq.jetty9.util.log.StdErrLog
16:28:28.951 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:28:28.977 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
16:28:28.977 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
16:28:28.979 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
.16:28:29.001 INFO - Using the passthrough mode handler
2017-09-21 16:28:29.025:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-09-21 16:28:29.049:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@2e005c4b{/,null,STARTING} has uncovered http methods for path: /
2017-09-21 16:28:29.053:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@2e005c4b{/,null,AVAILABLE}
2017-09-21 16:28:29.065:INFO:osjs.AbstractConnector:main: Started ServerConnector@10e31a9a{HTTP/1.1,[http/1.1]}{0.0.0.0:30001}
2017-09-21 16:28:29.066:INFO:osjs.Server:main: Started @725ms
16:28:29.066 INFO - Selenium Grid node is up and ready to register to the hub
16:28:29.077 INFO - Registering the node to the hub: http://localhost:4444/grid/register
...16:28:29.785 INFO - [SL] Account max. concurrency fetched from https://saucelabs.com/rest/v1/users/QUU903
16:28:29.788 INFO - Registered a node https://ondemand.saucelabs.com:443
16:28:29.789 INFO - The node is registered to the hub and ready to use
Sauce Labs node started!
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
16:28:30.198 ERROR - [DS]  A downloaded docker-selenium image was not found!
16:28:30.198 ERROR - [DS]  A downloaded docker-selenium image was not found!
16:28:34.487 [qtp2041605291-27] WARN  o.s.jetty9.server.HttpChannel - /grid/register
java.security.InvalidParameterException: Error: Host name may not be null
	at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:357)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:103)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
16:28:34.657 [qtp2041605291-19] WARN  o.s.jetty9.server.HttpChannel - /grid/register
java.security.InvalidParameterException: Error: Host name may not be null
	at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:357)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:103)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
16:31:38.270 INFO - Marking the node http://172.17.0.2:30000 as down: cannot reach the node for 2 tries
16:33:13.292 INFO - Unregistering the node http://172.17.0.2:30000 because it's been down for 95022 milliseconds
16:33:13.292 WARN - Cleaning up stale test sessions on the unregistered node http://172.17.0.2:30000

**Comment by diemol** [comment]
Just edited your comment to make it more readable.

@srinuuk what is efe1c0dcbe15 and d0b50b81dda6? Where do those images come from? 
Why don't you use our images?

**Comment by srinuuk** [comment]
I have put a note in my previous comment. Yesterday I have pulled latest code of zalenium and Selenium and rebuilt the images by adding our internal proxy in Docker file as below
ENV http_proxy <proxy>
ENV https_proxy <Proxy>
ENV no_proxy 127.0.0.1,localhost,0.0.0.0

If we do not set internal proxy we cannot run any tests.

**Comment by diemol** [comment]
Can you try to do it like it was show in this [comment](https://github.com/zalando/zalenium/issues/198#issuecomment-324433665) please. At least until we implement #198

**Comment by srinuuk** [comment]
Tried but no luck :-(
docker run -e "http_proxy=XXXXXXXXX" -e "https_proxy=XXXXXXXXX" --rm -ti --name zalenium -p 4444:4444 -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY -v /tmp/videos:/home/seluser/videos -v /var/run/docker.sock:/var/run/docker.sock --privileged dosel/zalenium start --sendAnonymousUsageInfo false --sauceLabsEnabled true

Here is the log

Docker binary already present, will use that one.
Docker version 17.03.0-ce, build 60ccb22
-- LOG 19:08:18:559921706 Ensuring docker works...
-- LOG 19:08:18:592394082 Ensuring no stale Zalenium related containers are still around...
-- LOG 19:08:18:609323599 Ensuring docker-selenium is available...
-- LOG 19:08:19:146144147 Running additional checks...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
19:08:19.932 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
19:08:19.937 INFO - Launching Selenium Grid hub
19:08:20.474 INFO - binding de.zalando.ep.zalenium.servlet.LivePreviewServlet to /grid/admin/LivePreviewServlet/*
19:08:20.475 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumConsoleServlet to /grid/admin/ZaleniumConsoleServlet/*
19:08:20.476 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumResourceServlet to /grid/admin/ZaleniumResourceServlet/*
19:08:20.477 INFO - binding de.zalando.ep.zalenium.dashboard.DashboardCleanupServlet to /grid/admin/DashboardCleanupServlet/*
19:08:20.630 INFO - Will listen on 4445
19:08:20.719 INFO - Nodes should register to http://172.17.0.2:4445/grid/register/
19:08:20.719 INFO - Selenium Grid hub is up and running
Selenium Hub started!
Starting DockerSeleniumStarter node...
19:08:20.996 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
19:08:20.998 INFO - Launching a Selenium Grid node
2017-09-21 19:08:21.435:INFO::main: Logging initialized @670ms to org.seleniumhq.jetty9.util.log.StdErrLog
19:08:21.476 INFO - Driver class not found: com.opera.core.systems.OperaDriver
19:08:21.501 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
19:08:21.501 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
19:08:21.502 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
19:08:21.527 INFO - Using the passthrough mode handler
2017-09-21 19:08:21.556:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-09-21 19:08:21.579:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@2e005c4b{/,null,STARTING} has uncovered http methods for path: /
2017-09-21 19:08:21.583:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@2e005c4b{/,null,AVAILABLE}
2017-09-21 19:08:21.595:INFO:osjs.AbstractConnector:main: Started ServerConnector@10e31a9a{HTTP/1.1,[http/1.1]}{0.0.0.0:30000}
2017-09-21 19:08:21.595:INFO:osjs.Server:main: Started @830ms
19:08:21.595 INFO - Selenium Grid node is up and ready to register to the hub
19:08:21.607 INFO - Registering the node to the hub: http://localhost:4444/grid/register
.19:08:23.127 INFO - [DS] Capabilities grabbed from the docker-selenium image
19:08:23.133 INFO - Registered a node http://172.17.0.2:30000
19:08:23.133 INFO - The node is registered to the hub and ready to use
19:08:23.134 INFO - [DS]  Setting up 2 nodes...
19:08:23.138 INFO - 2 containers were created, it will take a bit more until all get registered.
...19:08:27.136 INFO - [DS] No container was created, will try again in a moment...
..19:08:30.137 INFO - Registered a node http://172.17.0.3:40000
.19:08:30.642 INFO - [DS] Container zalenium_40000 is up after ~4 seconds...
...............StarterRemoteProxy failed to register to the hub after 30s seconds, failing...

**Comment by diemol** [comment]
No @srinuuk, you did not check the linked comment.

This is what it says, to build the images like this example:

```
FROM elgalu/selenium
ENV http_proxy=http://myproxy.example.com:8080 https_proxy=http://myproxy.example.com:8080 no_proxy=172.16/12, 10.0.0.0/8, *.local, 169.254/16, 192.168.99.*, localhost, 127.0.0.1
``` 

and for Zalenium you could:

```
FROM dosel/zalenium
ENV http_proxy=http://myproxy.example.com:8080 https_proxy=http://myproxy.example.com:8080 no_proxy=172.16/12, 10.0.0.0/8, *.local, 169.254/16, 192.168.99.*, localhost, 127.0.0.1
``` 

**please replace the proxy values according to your needs**

**Comment by srinuuk** [comment]
Hi, Yes, that is how I built Docker images initially and tested. The error initially i posted is with the same process. I have given run command as followed with docker docker image names as efe1c0dcbe15(for zalenium) and d0b50b81dda6(for selenium). 

 docker run --rm -ti --name zalenium -p 4444:4444 \
    -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY \
    -v /tmp/videos:/home/seluser/videos \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --privileged efe1c0dcbe15 start --sendAnonymousUsageInfo false --seleniumImageName d0b50b81dda6 --sauceLabsEnabled true

**Comment by diemol** [comment]
Hi @srinuuk,

We just released https://github.com/zalando/zalenium/releases/tag/3.6.0e, which allows you to specify the proxy values and they get spread across containers.

Please check the [documentation](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#adding-proxy-configuration-to-the-containers) to see how to do it, so you do not need to build your own container now.

Let us know how it went.

**Comment by diemol** [comment]
@srinuuk in #198 it was reported that the proxy feature works. Since we have not gotten feedback about this, I will close this but feel free to reopen if a problem still exists.
