### ISSUE TITLE
Not able to run Parallel tests successfully

### ISSUE THREAD

**Issue by srinuuk** [zalando/zalenium#265]
First, Zalenium is awesome and it's really looking cool. It works perfectly with few sequential sessions. I am facing issue when I invoke job with multiple threads.
Here is the scenario:
System configuration:
Mac Pro 64GB RAM, 3.5GHz 6-core processor
Tried with latest docker images.
Zalenium invoked with below parameters
--chromeContainers 5 --firefoxContainers 3 --maxTestSessions 5 --maxDockerSeleniumContainers 10.
Invoked ~250 tests disabling video recording to save CPU utilization
Triggered to run 5 parallel tests at a time.
Four sessions created without any issues, 5th session it failed with below error:
(Note: sometimes all 5 sessions are created without any issues initially but later it's failing with same below error )
```
20:30:43.058 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, acceptSslCerts=true, screen-resolution=1024x768, tz=Europe/Berlin, browserName=chrome, maxInstances=1, screenResolution=1024x768, resolution=1024x768, version=61.0.3163.100, platform=LINUX}
20:30:43.578 INFO - Error forwarding the new session Error forwarding the request 172.17.0.15:40012 failed to respond
org.openqa.grid.internal.exception.NewSessionException: Error forwarding the request XXX.XX.X.XX:40012 failed to respond
	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:86)
```

when next 5 threads are invoked only 4 running and 1 is kept in queue. Even there are 10 instances available.One browser become orphan. In subsequence rounds, number of requests in a queue started increasing and number of instances that are running coming down one by one. Tests running for around 20hrs and not completed since most of the tests are in queue and not been allocated to available browsers. Also tried in Linux, I see same issue. Tried couple of times increasing and decreasing number of chrome sessions and also maxTest Sessions.
 
<img width="1239" alt="screen shot 2017-10-06 at 9 50 01 am" src="https://user-images.githubusercontent.com/19392432/31280874-d005a2d2-aa7b-11e7-97e4-06fca543b0be.png">

**Comment by elgalu** [comment]
Thanks:) can you check how much CPU and RAM is allocated to Docker for Mac? in the preferences.

**Comment by srinuuk** [comment]
Give full CPU to my Docker and almost half of available memory. 
CPU's: 6
Memory: 30GB
I don't think there is any issue with resources.  Initially tried with low system resources, HUB is hanging when requests started pilling up. Later give enough resources, now HUB is not hanging but requests are not being processed as expected. Interestingly requests getting queued up even though there are enough containers readily available.
Another observation. If I trigger new test independently on same HUB, requested is not queued, existing available container immediately allocated and processed. But existing requests in queue are not being allocated.

**Comment by diemol** [comment]
Hi @srinuuk, 

You start Zalenium with `--maxDockerSeleniumContainers 10` and `--chromeContainers 5 --firefoxContainers 3`. So you have 8 containers running and maximum you configured 10.


I see in your test capabilities that you request screenResolution=1024x768, but the default that Zalenium has is SCREEN_WIDTH=1900 x SCREEN_HEIGHT=1880.

Could it be possible that those 8 initial containers have the default screen resolution and therefore they never get used?

**Comment by borisivan** [comment]
For what it's worth, I see "Error forwarding the request" messages occasionally too. In a suite of 100 tests running across 6 parallel chrome containers, once every 5 or 6 suite runs, I'll see this once or twice. Tests are otherwise running fine in parallel. For me, it does seem to be a race condition or some other such problem, But it does look like there is a problem.

my stack trace:

[15:40:48 INFO  ProtocolHandshake             ] Detected dialect: OSS
org.openqa.selenium.WebDriverException: **cannot forward the request 172.17.0.3:40000 failed to respond**
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:310)
	at (obfuscated -- this is my test code)
	at (obfuscated -- this is my test code)
	at (obfuscated -- this is my test code)
	at (obfuscated -- this is my test code)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:197)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:209)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:56)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: cannot forward the request 172.17.0.3:40000 failed to respond
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'ci-sles12-slave-336', ip: '127.0.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '3.12.60-52.54-default', java.version: '1.8.0_60'
Driver info: driver.version: unknown
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:135)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:84)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)

**Comment by srinuuk** [comment]
Removed setting 'screenResolution=1024x768' and tried but simillar result.

Not creating new containers. Requests pilling up in a queue. Please find the attached updated screenshot.

<img width="1234" alt="screen shot 2017-10-12 at 12 34 46 pm" src="https://user-images.githubusercontent.com/19392432/31507762-d537d838-af49-11e7-873d-0ac112303497.png">

**Comment by diemol** [comment]
I see in the image 6 nodes/containers up, 3 Chrome and 3 Firefox. The 3 Chromes are being used, and none of the Firefox are used.

Also 13 requests waiting for a node to be free, seems that all of them need a Chrome browser.

Questions:
* How many threads are you using in your tests? If requests pile up is probably because you are using a higher number of threads than configured nodes to start.
* Do you need the Firefox containers up? Seems you need only Chrome ones, and with the limit of containers, requests pile up.

In general, if you are running your tests in Chrome with 5 threads, you should configure Zalenium to start with 5 Chrome nodes.

**Comment by diemol** [comment]
Were you able to solve this issue @srinuuk?

**Comment by diemol** [comment]
I'll close this issue since there has been no activity. Feel free to reopen in case a problem still exists.
