### ISSUE TITLE
Throws exception on Fedora

### ISSUE THREAD

**Issue by jkandasa** [zalando/zalenium#276]
Host OS: Fedora 26 [4.13.4-200.fc26.x86_64]
```
[root@jkandasa ~]# docker -v
Docker version 1.13.1, build b5e3294/1.13.1
```
Throws exception when we run `dosel/zalenium` on Fedora,
```bash
 docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    --privileged dosel/zalenium start
``` 

Exception:
```java
Exception in thread "Thread-10" java.lang.NullPointerException: path is 'null'.
	at jersey.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
	at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:59)
	at com.spotify.docker.client.DefaultDockerClient.inspectContainer(DefaultDockerClient.java:986)
	at de.zalando.ep.zalenium.container.DockerContainerClient.getZaleniumNetwork(DockerContainerClient.java:342)
	at de.zalando.ep.zalenium.container.DockerContainerClient.createContainer(DockerContainerClient.java:197)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:482)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.lambda$createContainersOnStartup$3(DockerSeleniumStarterRemoteProxy.java:586)
	at java.lang.Thread.run(Thread.java:748)
```

##### Root case of the issue:
`[0-9a-f]{64}$` this regex parse containerId. Assumes that each line ends with containerId, but in Fedora it is not! ends with `.scope` https://github.com/zalando/zalenium/blob/b6223e5407fdda5bb74441a7a79219a850456d4d/scripts/zalenium.sh#L267

```bash
bash-4.2# grep docker /proc/self/cgroup
11:cpuset:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
10:cpu,cpuacct:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
9:memory:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
8:pids:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
7:devices:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
6:net_cls,net_prio:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
5:perf_event:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
4:blkio:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
3:hugetlb:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
2:freezer:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
1:name=systemd:/system.slice/docker-a414f61624e63036d028d59a710e756047325d1fc3ffc05096d78d6aeb254f26.scope
```

https://github.com/zalando/zalenium/issues/232 looks similar

**Comment by jkandasa** [comment]
Docker in Docker (DinD)
```bash
# grep docker /proc/self/cgroup
11:pids:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
10:perf_event:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
9:freezer:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
8:devices:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
7:hugetlb:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
6:net_cls,net_prio:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
5:cpuset:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
4:cpu,cpuacct:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
3:memory:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
2:blkio:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
1:name=systemd:/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope/docker/5784f85a36c3b881097f1bc7e3277dfbdadca72b067a49913f4a3e4d29ac130a
0::/system.slice/docker-c7d4894d1a3c882fcbb0e43d43bde10f7bc80cdfa9570c1a97f9c3c5a1449175.scope

```

**Comment by diemol** [comment]
Thanks for the issue and the PR @jkandasa 
We just released this, check https://github.com/zalando/zalenium/releases/tag/3.6.0c
Please report back so we can close this issue.

**Comment by diemol** [comment]
Thanks for contributing @jkandasa!
