### ISSUE TITLE
Zalenium error and hanging docker engine after clearing logs

### ISSUE THREAD

**Issue by dforrest88** [zalando/zalenium#287]
Zalenium Image Version(s):  
3.5.3c

Docker Version:  
17.03.2-ce

OS: 
AWS -> amzn-ami-2017.03.f-amazon-ecs-optimized (ami-9eb4b1e5)

Docker Command to start Zalenium:  
docker run -d --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium:3.5.3c start --videoRecordingEnabled false --chromeContainers 0 --firefoxContainers 0 --timeZone EST --debugEnabled true

NOTE: This has happened several times to me over the past couple of months.

I had a Zalenium instance that was up and running just fine for a few weeks, however after cleaning the logs, I started getting errors in my tests on the client side that it couldn't start a new remote session. When I logged into the instance, I was unable to run a docker ps command and it just hung. I was however able to get the logs for the running Zalenium container and saw the below error as the last message.

Ultimately, I had to restart the docker engine and start Zalenium back up in order to fix the problem. 

`11:06:06.958 DEBUG - http://172.17.0.3:40235 Error while executing the output.readFully()
java.lang.RuntimeException: java.io.IOException: Connection reset by peer
    at com.google.common.base.Throwables.propagate(Throwables.java:241)
    at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:58)
    at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:35)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
    at com.spotify.docker.client.DefaultLogStream.readFully(DefaultLogStream.java:77)
    at de.zalando.ep.zalenium.container.DockerContainerClient.executeCommand(DockerContainerClient.java:115)
    at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:392)
    at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.cleanupNode(DockerSeleniumRemoteProxy.java:468)
    at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.shutdownNode(DockerSeleniumRemoteProxy.java:481)
    at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.afterSession(DockerSeleniumRemoteProxy.java:255)
    at org.openqa.grid.internal.TestSlot.performAfterSessionEvent(TestSlot.java:247)
    at org.openqa.grid.internal.Registry._release(Registry.java:129)
    at org.openqa.grid.internal.Registry.access$100(Registry.java:45)
    at org.openqa.grid.internal.Registry$1.run(Registry.java:112)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection reset by peer
    at jnr.enxio.channels.NativeSocketChannel.read(NativeSocketChannel.java:82)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
    at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
    at org.apache.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:93)
    at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:102)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:296)
    at com.google.common.io.ByteStreams.read(ByteStreams.java:859)
    at com.spotify.docker.client.LogReader.nextMessage(LogReader.java:49)
    at com.spotify.docker.client.DefaultLogStream.computeNext(DefaultLogStream.java:56)
    ... 14 more`

**Comment by diemol** [comment]
Hi @dforrest88,

I would imagine that the docker daemon gets over used by the amount of containers created and destroyed. 

To be honest, I don't have an answer for this because we don't have long running Zalenium deployments, we normally spin it up before the tests and destroy it after the tests ended (which is generally the common approach with docker-based grids).

Do you need to have the AWS instance running 24hrs? Maybe it is cheaper to schedule it and then implicitly the daemon gets restarted every day.

**Comment by diemol** [comment]
I'll close this issue since I think there is no action item to do. But if you come up with an idea to handle this, please let us know and we could work together on it. We also accept PRs!
