### ISSUE TITLE
ContainerNotFoundException when setting up nodes

### ISSUE THREAD

**Issue by arielschiavoni** [zalando/zalenium#40]
Hi there, first of all thanks for the work done on this very helpful tool.

I tried `zalenium` a couple of days ago and everything worked out of the box. However today when I run zalenium I get `ContainerNotFoundException` which seems to prevent the containers from been created an attached to the grid/hub.

```
docker run --rm -ti \
    --name selenium \
    -p 4444:4444 \
    -p 5555:5555 \
    -e DOCKER=1.12 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    dosel/zalenium:2.53.1k start
```

I noticed `zalenium:2.53.1k` has been recently released so I also tried to run `zalenium:2.53.1j` which throws the same exception.

```
11:51:25.558 INFO - [DS]  Setting up 2 nodes...
11:51:27.418 ERROR - [DS] com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: da227fb1fe4f543c124a59f8e79237538116e22032597f49f5fd10e8f4237043
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: da227fb1fe4f543c124a59f8e79237538116e22032597f49f5fd10e8f4237043
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:613)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:601)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:395)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy$1.run(DockerSeleniumStarterRemoteProxy.java:436)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/da227fb1fe4f543c124a59f8e79237538116e22032597f49f5fd10e8f4237043/start: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2084)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2045)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:609)
	... 3 more
```

**Environment**
OS: macOS Sierra
Docker Version: 1.12.3

**Logs**

```
Docker version 1.12.3, build 6b644ec
Starting Nginx reverse proxy...
Starting Selenium Hub...
..11:51:16.288 INFO - Launching Selenium Grid hub
...11:51:17.143 INFO - binding de.zalando.tip.zalenium.servlet.live to /grid/admin/live/*
log4j:WARN No appenders could be found for logger (org.seleniumhq.jetty9.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
.11:51:17.299 INFO - Will listen on 4445
11:51:17.511 INFO - Will listen on 4445
.11:51:17.699 INFO - Nodes should register to http://172.17.0.2:4445/grid/register/
11:51:17.699 INFO - Selenium Grid hub is up and running
Selenium Hub started!
Starting DockerSeleniumStarter node...
.11:51:18.273 INFO - Launching a Selenium Grid node
....11:51:19.008 INFO - Java: Oracle Corporation 25.111-b14
11:51:19.009 INFO - OS: Linux 4.4.27-moby amd64
11:51:19.021 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
11:51:19.185 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
11:51:19.187 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
11:51:19.190 INFO - Driver class not found: com.opera.core.systems.OperaDriver
11:51:19.193 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
11:51:19.197 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
11:51:19.200 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
11:51:19.202 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
.11:51:19.321 INFO - Version Jetty/5.1.x
11:51:19.328 INFO - Started HttpContext[/selenium-server,/selenium-server]
11:51:19.333 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@3439f68d
11:51:19.333 INFO - Started HttpContext[/wd,/wd]
11:51:19.333 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
11:51:19.333 INFO - Started HttpContext[/,/]
11:51:19.343 INFO - Started SocketListener on 0.0.0.0:30000
11:51:19.343 INFO - Started org.openqa.jetty.jetty.Server@30b8a058
11:51:19.344 INFO - Selenium Grid node is up and ready to register to the hub
11:51:19.460 INFO - Starting auto registration thread. Will try to register every 5000 ms.
11:51:19.461 INFO - Registering the node to the hub: http://localhost:4444/grid/register
DockerSeleniumStarter node started!
Sauce Labs not enabled...
Browser Stack not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando-incubator/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
Sending info to GA
11:51:25.540 INFO - [DS] Capabilities fetched from https://raw.githubusercontent.com/elgalu/docker-selenium/latest/capabilities.json
11:51:25.550 INFO - Registered a node http://172.17.0.2:30000
11:51:25.552 INFO - The node is registered to the hub and ready to use
11:51:25.558 INFO - [DS]  Setting up 2 nodes...
11:51:27.418 ERROR - [DS] com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: da227fb1fe4f543c124a59f8e79237538116e22032597f49f5fd10e8f4237043
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: da227fb1fe4f543c124a59f8e79237538116e22032597f49f5fd10e8f4237043
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:613)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:601)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:395)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy$1.run(DockerSeleniumStarterRemoteProxy.java:436)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/da227fb1fe4f543c124a59f8e79237538116e22032597f49f5fd10e8f4237043/start: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2084)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2045)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:609)
	... 3 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
11:51:27.865 ERROR - [DS] com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 0113a0ae4c20241b923bb1ece434306153a333df953e830877ec20936a321067
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 0113a0ae4c20241b923bb1ece434306153a333df953e830877ec20936a321067
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:613)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:601)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:395)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy$1.run(DockerSeleniumStarterRemoteProxy.java:436)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/0113a0ae4c20241b923bb1ece434306153a333df953e830877ec20936a321067/start: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2084)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2045)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:609)
	... 3 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
11:51:28.326 ERROR - [DS] com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: c6282b1e2c445f58c2db8f7fc8a22f4228f6850f5180e26dcb2952c51fc8a10c
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: c6282b1e2c445f58c2db8f7fc8a22f4228f6850f5180e26dcb2952c51fc8a10c
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:613)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:601)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:395)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy$1.run(DockerSeleniumStarterRemoteProxy.java:436)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/c6282b1e2c445f58c2db8f7fc8a22f4228f6850f5180e26dcb2952c51fc8a10c/start: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2084)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2045)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:609)
	... 3 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
11:51:28.797 ERROR - [DS] com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: dc057eb1ef902e5eb22a7b76af16215312b840b20250ac1dbae561b5b02faf6a
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: dc057eb1ef902e5eb22a7b76af16215312b840b20250ac1dbae561b5b02faf6a
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:613)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:601)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:395)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy$1.run(DockerSeleniumStarterRemoteProxy.java:436)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/dc057eb1ef902e5eb22a7b76af16215312b840b20250ac1dbae561b5b02faf6a/start: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2084)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2045)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:609)
	... 3 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
11:51:29.256 ERROR - [DS] com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 2a524c926e406c458cde93344547812bc6062e9dd81e685f1947aec267a62136
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 2a524c926e406c458cde93344547812bc6062e9dd81e685f1947aec267a62136
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:613)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:601)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:395)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy$1.run(DockerSeleniumStarterRemoteProxy.java:436)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/2a524c926e406c458cde93344547812bc6062e9dd81e685f1947aec267a62136/start: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2084)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2045)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:609)
	... 3 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
11:51:29.817 ERROR - [DS] com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 85d9592c6c272216500f227d4b9e4d2228d7e64257d5ef74a4c1a201b00ce259
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 85d9592c6c272216500f227d4b9e4d2228d7e64257d5ef74a4c1a201b00ce259
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:613)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:601)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:395)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy$1.run(DockerSeleniumStarterRemoteProxy.java:436)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/85d9592c6c272216500f227d4b9e4d2228d7e64257d5ef74a4c1a201b00ce259/start: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2084)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2045)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:609)
	... 3 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by diemol** [comment]
Hi @arielschiavoni,

Thanks for trying Zalenium! 

Please try with the following command

```sh
docker run --rm -ti \
    --name zalenium \
    -p 4444:4444 \
    -p 5555:5555 \
    -e DOCKER=1.12 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    dosel/zalenium:2.53.1k start
``` 

If you note, the only difference in the command is the name of the container **zalenium**. 

We need to create the container with that name because a network inside docker is created with the name **zalenium**. With this, all containers can locate each other without so much hassle.

Please give it a try and let us know how it goes.

**Comment by arielschiavoni** [comment]
Hi @diemol,

When using **zalenium** as the container name everything works as expected.
It would be nice to add this to the `README.md` so I am going to send a PR.

Thank you very much.
