### ISSUE TITLE
Cannot add zalenium cookies

### ISSUE THREAD

**Issue by monkpit** [zalando/zalenium#413]
Zalenium Image Version(s):  
dosel/zalenium:latest
eglau/selenium:latest

Docker Version:  17.06.0-ce
If using docker-compose, version:  n/a
OS: CentOS Linux 7 (3.10.0)
Docker Command to start Zalenium:

```
  docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    -e PULL_SELENIUM_IMAGE=true \
    -e SELENIUM_CONTAINER_LABELS=io.rancher.container.network=true \
    -e SELENIUM_WAIT_FOR_CONTAINER=false \
    --privileged dosel/zalenium start --timeZone America/Chicago
```

If using Kubernetes, specify your environment, and if relevant your manifests:  n/a

## Expected Behavior -

Should be able to set `zaleniumMessage` cookie without error. Attempting to follow example under section "Referencing test steps in the recorded video" on [this page](https://zalando.github.io/zalenium/). I am using Protractor to write my tests, and adding the cookie like this:

`browser.manage().addCookie("zaleniumMessage", "Test Message");`

In the zalenium container logs I see `ERROR - cannot forward the request null`.
I see no errors in the selenium container logs.
I get the same issue if I try to set `zaleniumTestPassed`.

This indirectly causes all other test cases to fail with `Session [f36b75eca4050b7efc9917f3ba625022] was terminated due to PROXY_REREGISTRATION`.

## Actual Behavior -

Selenium dies with `NullPointerException`

```
1/22/2018 4:56:49 PM16:56:49.806 ERROR - cannot forward the request null
1/22/2018 4:56:49 PMjava.lang.NullPointerException
1/22/2018 4:56:49 PM	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.beforeCommand(DockerSeleniumRemoteProxy.java:230)
1/22/2018 4:56:49 PM	at org.openqa.grid.internal.TestSession.forward(TestSession.java:236)
1/22/2018 4:56:49 PM	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardRequest(RequestHandler.java:98)
1/22/2018 4:56:49 PM	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:132)
1/22/2018 4:56:49 PM	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:84)
1/22/2018 4:56:49 PM	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
1/22/2018 4:56:49 PM	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
1/22/2018 4:56:49 PM	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.Server.handle(Server.java:561)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:334)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:104)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
1/22/2018 4:56:49 PM	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
1/22/2018 4:56:49 PM	at java.lang.Thread.run(Thread.java:748)
```

**Comment by diemol** [comment]
Hi @monkpit,

That's weird, let me check it and I'll get back to you.

**Comment by diemol** [comment]
I was able to reproduce it. It is kind of strange since it does not happen with the Java bindings, but it does with Protractor.

**Comment by diemol** [comment]
Seems that in Protractor is is needed to add the cookie in a slight different way:
`browser.manage().addCookie({ name: 'zaleniumMessage', value: 'Test Message'});`

But of course you could not see the real error because Zalenium was breaking your test. Sorry about that :)
https://stackoverflow.com/questions/47217572/browser-manage-addcookie-returns-error-missing-name

We have fixed that and we will release soon, for now you can use the syntax above to send the cookie.

Thanks for reporting this.

**Comment by monkpit** [comment]
Awesome! Thank you :)

**Comment by monkpit** [comment]
So it turns out there is an error in the Protractor Typescript definitions - the `addCookie` signature is defined as:

```

  /**
   * Schedules a command to add a cookie.
   * @param {string} name The cookie name.
   * @param {string} value The cookie value.
   * @param {string=} opt_path The cookie path.
   * @param {string=} opt_domain The cookie domain.
   * @param {boolean=} opt_isSecure Whether the cookie is secure.
   * @param {(number|!Date)=} opt_expiry When the cookie expires. If specified
   *     as a number, should be in milliseconds since midnight,
   *     January 1, 1970 UTC.
   * @return {!promise.Promise<void>} A promise that will be resolved
   *     when the cookie has been added to the page.
   */
  addCookie(name: string, value: string, opt_path?: string, opt_domain?: string, opt_isSecure?: boolean, opt_expiry?: number | Date): promise.Promise<void>;
```

However, the actual protractor command expects an OBJECT, not individual parameters. This was apparently added as of Protractor 5.0. Thanks for your help in figuring this out, I will mention you when I create a PR against the typescript definitions. :beers:
