### ISSUE TITLE
Zalenium can't delete selenium containers (Kubernetes)

### ISSUE THREAD

**Issue by odracci** [zalando/zalenium#431]
Zalenium Image Version(s):  
3.8.1i
Docker Version:  
1.13.1
OS: 
Debian jessie
Docker Command to start Zalenium:  
Using official [chart](https://github.com/zalando/zalenium/tree/master/docs/k8s/helm/local/zalenium) running on Kubernetes
Kops 1.8.0
Kubernetes v1.8.4

## Expected Behavior -
I'm using Selenium and Zalenium deletes pods when the tests are finished.

## Actual Behavior -
Zalenium doesn't delete pods when the tests are finished, it reaches the max number of docker selenum containers

```
12:02:01.771 WARN - http://100.119.224.190:40002 java.lang.IllegalStateException: Not a JSON Object: null
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at de.zalando.ep.zalenium.dashboard.Dashboard.synchronizeExecutedTestsValues(Dashboard.java:153)
	at de.zalando.ep.zalenium.dashboard.Dashboard.updateDashboard(Dashboard.java:67)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.cleanupNode(DockerSeleniumRemoteProxy.java:528)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.shutdownNode(DockerSeleniumRemoteProxy.java:541)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.afterSession(DockerSeleniumRemoteProxy.java:273)
	at org.openqa.grid.internal.TestSlot.performAfterSessionEvent(TestSlot.java:253)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry._release(ZaleniumRegistry.java:121)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.lambda$terminate$0(ZaleniumRegistry.java:106)
	at java.lang.Thread.run(Thread.java:748)

12:02:51.790 INFO - [DS] Request has waited 30 attempts for a node, something went wrong with the previous attempts, creating a new node for {rotatable=false, nativeEvents=false, browserName=chrome, takesScreenshot=false, javascriptEnable
12:02:51.800 INFO - Pods in the list 20
12:02:51.800 WARN - [DS] Max. number of docker-selenium containers has been reached, no more will be created until the number decreases below 20.
12:02:51.801 INFO - [DS] No container was created, will try again in a moment...
```

**Comment by diemol** [comment]
Hi @odracci,

Does this always happen? Or at least some tests execute fine and this happens every now and then?

When you start Zalenium, is there something strange happening in the Zalenium pod? A warning, error...

In the meantime, we will add some NPE there.

**Comment by diemol** [comment]
Hi @odracci,

I added some validations to control this exception, it should be released soon.

In the meantime, would it be possible for you to provide more info?

**Comment by odracci** [comment]
Hi @diemol,

Thank you for your answer, I ran the command described in https://github.com/zalando/zalenium/issues/99#issuecomment-295814318 and it deleted `executedTestsInfo.json`.

Creating `executedTestsInfo.json` manually solved the issue.

**Comment by diemol** [comment]
That's great, thanks for writing back. I'll close this issue then.
