### ISSUE TITLE
org.openqa.selenium.WebDriverException: Error forwarding the new session Request timed out waiting for a node to become available. Command duration or timeout

### ISSUE THREAD

**Issue by gsaimadhu** [zalando/zalenium#567]
Thanks for Zalenium. Currently we are facing a regression issue with Zalenium. This is a blocker for us.
I tried with various commands before posting this issue. I think --add-host parameter while starting zalenium seems to have regression issue. Please help ASAP.

Zalenium Image Version(s):  
Using webdriver 3.11.0 client and Zalenium latest version.
# docker images | grep zalenium
dosel/zalenium                                                     latest              6a8d6e5f89b4        2 days ago          792MB
# docker images | grep selenium
elgalu/selenium                                                    latest              d48abad5816f        4 days ago          1.37GB
# 

Docker Version:  
# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

If using docker-compose, version:  
Not using docker-compose

OS: 
centos7
# uname -a
Linux apim-centos7-agent22 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Docker Command to start Zalenium:  
docker run --rm -t --name zalenium --net=host       -v /var/run/docker.sock:/var/run/docker.sock       -v /tmp/videos:/home/seluser/videos   --add-host "t1.l7tech.com:$ipa" --add-host "tenant2.l7tech.com:$ipa" --add-host "tenant3.l7tech.com:$ipa"  --add-host "t4.l7tech.com:$ipa"  --add-host "t12345.l7tech.com:$ipa"   --add-host "t6.l7tech.com:$ipa"   --add-host "t7.l7tech.com:$ipa"   --add-host "t8.l7tech.com:$ipa"   --add-host "tnt9.l7tech.com:$ipa"   --add-host "t10.l7tech.com:$ipa"   --add-host "televen.l7tech.com:$ipa"  --privileged dosel/zalenium start  --desiredContainers 24 --maxDockerSeleniumContainers 30 --maxTestSessions 1  > ZaleniumStartLogs.log &

## Expected Behavior -
Browser should be opened successfully

## Actual Behavior -
[14:06:28][Step 2/2] Conneting to remote webdriver @ : apim-centos7-agent2.l7tech.com
[14:06:28][Step 2/2] May 09, 2018 2:06:28 PM org.openqa.selenium.remote.DesiredCapabilities chrome
[14:06:28][Step 2/2] INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
[14:06:29][Step 2/2] Remote debugging can be done, by adding delay time in first thread in config sheet
[14:06:29][Step 2/2] main delay time set to 4 min.
[14:08:28][Step 2/2] org.openqa.selenium.WebDriverException: Error forwarding the new session Request timed out waiting for a node to become available.
[14:08:28][Step 2/2] Command duration or timeout: 600.17 seconds
[14:08:28][Step 2/2] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:08:28][Step 2/2] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:08:28][Step 2/2] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:08:28][Step 2/2] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:08:28][Step 2/2] 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
[14:08:28][Step 2/2] 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
[14:08:28][Step 2/2] 	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
[14:08:28][Step 2/2] 	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
[14:08:28][Step 2/2] 	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
[14:08:28][Step 2/2] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[14:08:28][Step 2/2] 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[14:08:29][Step 2/2] 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[14:08:29][Step 2/2] 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
[14:08:29][Step 2/2] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[14:08:29][Step 2/2] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[14:08:29][Step 2/2] 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[14:08:29][Step 2/2] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:08:29][Step 2/2] 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[14:08:29][Step 2/2] 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
[14:08:29][Step 2/2] 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
[14:08:29][Step 2/2] 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
[14:08:29][Step 2/2] 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
[14:08:29][Step 2/2] 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)
[14:08:29][Step 2/2] 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)
[14:08:29][Step 2/2] 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:145)
[14:08:29][Step 2/2] 	at com.qa.generic.automation.gui.plugins.Selenium.Setup.init(Setup.java:412)
[14:08:29][Step 2/2] 	at com.qa.generic.automation.gui.plugins.Selenium.Setup.OpenBrowserSession(Setup.java:166)
[14:08:29][Step 2/2] 	at com.qa.generic.automation.gui.plugins.Selenium.Setup.execute(Setup.java:138)
[14:08:29][Step 2/2] 	at com.qa.framework.adapter.GlobalPluginManager.invokePackageLevelTranslatorSetupPlugin(GlobalPluginManager.java:341)
[14:08:29][Step 2/2] 	at com.qa.framework.adapter.GenericAdapter.beforeMethod(GenericAdapter.java:432)
[14:08:29][Step 2/2] 	at com.qa.framework.adapter.GenericAdapter.invokeAdapter(GenericAdapter.java:686)
[14:08:29][Step 2/2] 	at com.qa.framework.executor.TestScenarioRunner.callAdapter(TestScenarioRunner.java:829)
[14:08:29][Step 2/2] 	at com.qa.framework.executor.TestScenarioRunner.runTestScenario(TestScenarioRunner.java:387)
[14:08:29][Step 2/2] 	at com.qa.framework.executor.TestTypeRunner.runAllTestScenarios(TestTypeRunner.java:489)
[14:08:29][Step 2/2] 	at com.qa.framework.executor.Gift.run(Gift.java:532)
[14:08:29][Step 2/2] 	at java.lang.Thread.run(Thread.java:745)
[14:08:29][Step 2/2] Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session Request timed out waiting for a node to become available.
[14:08:29][Step 2/2] Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
[14:08:29][Step 2/2] System info: host: '', ip: '10.7.33.159', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.21.1.el7.x86_64', java.version: '1.8.0_121'
[14:08:29][Step 2/2] Driver info: driver.version: unknown
[14:08:29][Step 2/2] 	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:118)
[14:08:29][Step 2/2] 	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
[14:08:29][Step 2/2] 	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)
[14:08:29][Step 2/2] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
[14:08:29][Step 2/2] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
[14:08:29][Step 2/2] 	at io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:170)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:533)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
[14:08:29][Step 2/2] 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
[14:08:29][Step 2/2] 	at java.lang.Thread.run(Thread.java:748)

**Comment by gsaimadhu** [comment]
Zalenium startup logs are attached for troubleshooting.
[ZaleniumStartLogs.log](https://github.com/zalando/zalenium/files/1989989/ZaleniumStartLogs.log)

**Comment by pearj** [comment]
This seems to be the problem:
```
02:20:08.167 [qtp1481818223-16] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register.
```

**Comment by gsaimadhu** [comment]
Pearj, 
how to resolve this:
02:20:08.167 [qtp1481818223-16] WARN  d.z.e.z.c.DockerContainerClient - No container id for zalenium - 127.0.0.1, can't register.

**Comment by pearj** [comment]
`--net=host` is your problem. That method is no longer supported.  You need to let it use the normal docker network. Use `-p 4444:4444` instead of `--net=host`. Then the grid will be available at localhost:4444.

**Comment by gsaimadhu** [comment]
Excellent, it worked. Thanks Pearj for quick response.

**Comment by diemol** [comment]
Thanks for the feedback @gsaimadhu, closing this issue.
