### ISSUE TITLE
502 Bad Gateway nginx/1.10.3 (Ubuntu) while deploying k8s cluster

### ISSUE THREAD

**Issue by sagarpinninti** [zalando/zalenium#576]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

Docker Version:  

1.12.6 
If using docker-compose, version:  

OS: RHEL7

Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  
k8s (1.7.10) multinode cluster installed on RHLE7.
## Expected Behavior -
Back-off restarting failed container Error syncing pod
Pod log - org.openqa.grid.common.exception.GridConfigurationException: Error creating class with de.zalando.ep.zalenium.registry.ZaleniumRegistry : null
 	at org.openqa.grid.web.Hub.<init>(Hub.java:94)
 	at org.openqa.grid.selenium.GridLauncherV3$2.launch(GridLauncherV3.java:290)
 	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:121)
 	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:81)
 Caused by: java.lang.ExceptionInInitializerError
 	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:71)
 	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:59)
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 	at java.lang.Class.newInstance(Class.java:442)
 	at org.openqa.grid.web.Hub.<init>(Hub.java:90)
 	... 3 more
 Caused by: java.lang.NullPointerException
 	at java.util.TreeMap.putAll(TreeMap.java:313)
 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:411)
 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:48)
 	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.deleteSeleniumPods(KubernetesContainerClient.java:393)
 	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.initialiseContainerEnvironment(KubernetesContainerClient.java:339)
 	at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:38)
 	at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
 	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:56)
 	... 11 more
## Actual Behavior -
application dashboard should work

**Comment by pearj** [comment]
That error looks unrelated to downloading videos. All that error says the selenium container hasn't started yet after waiting more than 3 minutes.  Are your tests starting at all?

**Comment by sagarpinninti** [comment]
The test are started now and it working perfectly ... thank you for the support and we can close the issue.

**Comment by bramvdklinkenberg** [comment]
@sagarpinninti could you check if you had the same issue as I am having right now, https://github.com/zalando/zalenium/issues/603? If so, how did you fix the rbac issue?

**Comment by bramvdklinkenberg** [comment]
@sagarpinninti thanks for the info! was that on a self setup k8s cluster with rbac enabled?
I am trying to deploy on an AKS cluster (Azure) but the cluster-admin clusterrole is not there (accessible).
Deployed it on a ACS (also Kubernetes) cluster and there I get it to work though. But both clusters don't even have rbac enabled... 
Locally I got it to run with minikube as well. So something happening on AKS... have to figure out what but no clue yet :).

**Comment by sagarpinninti** [comment]
Yes its on the self setup k8s with rbac enabled. Sorry i am not using AKS to do a  quick check.
