### ISSUE TITLE
Connection reset and connection refused

### ISSUE THREAD

**Issue by ezwanharun** [zalando/zalenium#600]
I have execute my 40 automation test via parallel test which consist of 10 nodes. I do encounter an issue where my test cases didnt run / failed in the middle of test due to above title. 

Zalenium Image Version(s): latest (3.12.0b)
Docker Version:  17.09.1-ce
OS: debian 9.3

Docker Command to start Zalenium:  
sudo docker run --rm -di --name ${bamboo.zaleniumName} -p ${bamboo.zaleniumPort}:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start --maxDockerSeleniumContainers ${bamboo.maxDockerSeleniumContainers} --desiredContainers ${bamboo.desiredContainers} --timeZone "Asia/Singapore" --videoRecordingEnabled ${bamboo.videoRecordingEnabled}
## Expected Behavior -
all 40 test cases should be able to executed
## Actual Behavior -
some test cases was terminated due to connection refused and some test cases that in queue is unable to start at all due to `DevToolsActivePort file doesn't exist` error message

trace log:
stake trace 1:
`org.openqa.selenium.WebDriverException: java.net.ConnectException: Connection refused (Connection refused)
Command duration or timeout: 0 milliseconds
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:319)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:413)
        at org.openqa.selenium.By$ByCssSelector.findElement(By.java:430)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:311)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:103)
        at com.sun.proxy.$Proxy20.findElement(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:186)
        at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
        at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
        at com.sun.proxy.$Proxy22.isDisplayed(Unknown Source)
        at org.openqa.selenium.support.ui.ExpectedConditions.isInvisible(ExpectedConditions.java:1405)
        at org.openqa.selenium.support.ui.ExpectedConditions.access$400(ExpectedConditions.java:44)
        at org.openqa.selenium.support.ui.ExpectedConditions$46.apply(ExpectedConditions.java:1393)
        at org.openqa.selenium.support.ui.ExpectedConditions$46.apply(ExpectedConditions.java:1389)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
        at com.ml.dashboard.pages.basePage.waitForInvisibilityOfElement(basePage.java:67)
        at com.ml.dashboard.pages.basePage.isElementDisappear(basePage.java:94)
        at com.ml.dashboard.pages.loans.BetterCash.BCPaySchedulePage.confirmPaySchedule(BCPaySchedulePage.java:35)
        at com.ml.dashboard.items.BetterCashItem.confirmPaymentSchedule(BetterCashItem.java:220)
        at com.ml.dashboard.stepDefs.BCStepdefs.completeTheOnBoardingProcess(BCStepdefs.java:103)
        at ✽.I complete the on boarding process(/Users/ezwan/Documents/Automation/ml-automated-functional-test/src/test/resources/features/BCOrganic.feature:57)
Caused by: org.openqa.selenium.WebDriverException: java.net.ConnectException: Connection refused (Connection refused)
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'ip-192-168-1-69.ec2.internal', ip: 'fe80:0:0:0:1438:2a59:7849:82e9%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_112'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$1(WebDriverServlet.java:251)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

stake trace 2:
`org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Command duration or timeout: 0 milliseconds
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:319)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:413)
        at org.openqa.selenium.By$ByCssSelector.findElement(By.java:430)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:311)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:103)
        at com.sun.proxy.$Proxy20.findElement(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:186)
        at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
        at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
        at com.sun.proxy.$Proxy22.isDisplayed(Unknown Source)
        at org.openqa.selenium.support.ui.ExpectedConditions.isInvisible(ExpectedConditions.java:1405)
        at org.openqa.selenium.support.ui.ExpectedConditions.access$400(ExpectedConditions.java:44)
        at org.openqa.selenium.support.ui.ExpectedConditions$46.apply(ExpectedConditions.java:1393)
        at org.openqa.selenium.support.ui.ExpectedConditions$46.apply(ExpectedConditions.java:1389)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
        at com.ml.dashboard.pages.basePage.waitForInvisibilityOfElement(basePage.java:67)
        at com.ml.dashboard.pages.basePage.isElementDisappear(basePage.java:94)
        at com.ml.dashboard.pages.loans.BetterCash.BCPaySchedulePage.confirmPaySchedule(BCPaySchedulePage.java:35)
        at com.ml.dashboard.items.BetterCashItem.confirmPaymentSchedule(BetterCashItem.java:220)
        at com.ml.dashboard.stepDefs.BCStepdefs.completeTheOnBoardingProcess(BCStepdefs.java:103)
        at ✽.I complete the on boarding process(/Users/ezwan/Documents/Automation/ml-automated-functional-test/src/test/resources/features/BCOrganic.feature:57)
Caused by: org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'ip-192-168-1-69.ec2.internal', ip: 'fe80:0:0:0:1438:2a59:7849:82e9%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_112'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$1(WebDriverServlet.java:251)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

stake trace 3 :
`Caused by: org.openqa.selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.9.0-6-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.05 seconds
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'c69595cbfe77', ip: '172.17.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-6-amd64', java.version: '1.8.0_171'
Driver info: driver.version: unknown
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'ip-192-168-1-69.ec2.internal', ip: 'fe80:0:0:0:1438:2a59:7849:82e9%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_112'
Driver info: driver.version: unknown
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfRes`

**Comment by diemol** [comment]
Hi @ezwanharun,

Could you please provide the logs from Zalenium?

**Comment by ezwanharun** [comment]
Hi @diemol 

`
61f-b37a-aa87f5ba19d0 (int. key, remote not contacted yet.) to http://172.17.0.4:40005/wd/hub at 4:31:29 PM","level":"INFO","level_value":20000,"application":"zalenium"}
{"@timestamp":"2018-06-01T16:32:48.935+08:00","@version":"1","message":"[d273b351f76d3edf384fc66219f2b2ddc86d35786971a8ab52204f4fd3db4976] has been idle [90372] which is more than [90000]","logger_name":"de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy","thread_name":"AutoStartProxyPoolPoller","level":"INFO","level_value":20000,"application":"zalenium"}
{"@timestamp":"2018-06-01T16:32:48.935+08:00","@version":"1","message":"[d273b351f76d3edf384fc66219f2b2ddc86d35786971a8ab52204f4fd3db4976] is stale.","logger_name":"de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy","thread_name":"AutoStartProxyPoolPoller","level":"INFO","level_value":20000,"application":"zalenium"}
{"@timestamp":"2018-06-01T16:32:48.935+08:00","@version":"1","message":"d273b351f76d3edf384fc66219f2b2ddc86d35786971a8ab52204f4fd3db4976 Shutting down node due to proxy being stuck | stale during a test.","logger_name":"de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy","thread_name":"AutoStartProxyPoolPoller","level":"INFO","level_value":20000,"application":"zalenium"}
{"@timestamp":"2018-06-01T16:32:48.953+08:00","@version":"1","message":"http://172.17.0.3:40000 [bash, -c, notify 'Zalenium', 'TEST TIMED OUT', --icon=/home/seluser/images/timeout.png]","logger_name":"de.zalando.ep.zalenium.container.DockerContainerClient","thread_name":"pool-3-thread-3","level":"INFO","level_value":20000,"application":"zalenium"}
{"@timestamp":"2018-06-01T16:32:49.011+08:00","@version":"1","message":"d273b351f76d3edf384fc66219f2b2ddc86d35786971a8ab52204f4fd3db4976 stop-video: Video recording is disabled","logger_name":"de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy","thread_name":"pool-3-thread-3","level":"INFO","level_value":20000,"application":"zalenium"}
{"@timestamp":"2018-06-01T16:32:49.017+08:00","@version":"1","message":"http://172.17.0.3:40000 [bash, -c, transfer-logs.sh]","logger_name":"de.zalando.ep.zalenium.container.DockerContainerClient","thread_name":"pool-3-thread-3","level":"INFO","level_value":20000,"application":"zalenium"}
{"@timestamp":"2018-06-01T16:32:49.058+08:00","@version":"1","message":"d273b351f76d3edf384fc66219f2b2ddc86d35786971a8ab52204f4fd3db4976 Logs copied to: /home/seluser/videos/logs/zalenium_Automation_Test_chrome_LINUX_20180601162420806_COMPLETED","logger_name":"de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy","thread_name":"pool-3-thread-3","level":"INFO","level_value":20000,"application":"zalenium"}
{"@timestamp":"2018-0 

`

**Comment by ezwanharun** [comment]
I saw there is some log mentioned that proxy was stuck or stale

**Comment by pearj** [comment]
@ezwanharun do you use any long sleeps in your test? Stale tests are ones which haven't sent any selenium commands in 90 seconds.  After that, zalenium terminates the test, that's what it looks like has happened here.

**Comment by XAMelleOH** [comment]
Use `--no-sandbox` and `--disable-dev-shm-usage` chrome params

**Comment by diemol** [comment]
Closing this issue since we didn't get more feedback from the OP.

If the issue still persists please create a new issue with updated data/info.
