### ISSUE TITLE
Kubernetes setup

### ISSUE THREAD

**Issue by DeChrish** [zalando/zalenium#671]
All the steps work fine.
Final step ' minikube service zalenium'  is not working. Browser open with BAD request.

**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

Docker Version:  

If using docker-compose, version:  

OS: 

Docker Command to start Zalenium:  

If using Kubernetes, specify your environment, and if relevant your manifests:  

Kubernetes: Local minikube

## Expected Behavior -
Grid should be up and running

## Actual Behavior -
502 Bad Gateway - http://192.168.99.100:31340/

**Comment by pearj** [comment]
If you want help you're going to have to at least provide some of the kubernetes logs.  Try going into the minikube web console and see if you can find out what is wrong.

**Comment by diemol** [comment]
Closing as we didn't get feedback from the OP.

**Comment by DeChrish** [comment]
@diemol / @pearj 
sorry for the delay, Below are the logs

Copying files for Dashboard...
cp: cannot create regular file '/home/seluser/videos/index.html': No such file or directory
Starting Nginx reverse proxy...
Starting Selenium Hub...
....07:03:50.036 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
07:03:50.138 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.07:03:50.433 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
.07:03:50.720 [main] WARN  d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/default/pods/zalenium. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "zalenium" is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:476)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:413)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:794)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:210)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:90)
	at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:48)
	at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:61)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:100)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:87)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.openqa.grid.web.Hub.<init>(Hub.java:94)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
	at java.util.Optional.map(Optional.java:215)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
07:03:50.721 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - About to clean up any left over selenium pods created by Zalenium
Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Error creating class with de.zalando.ep.zalenium.registry.ZaleniumRegistry : null
	at org.openqa.grid.web.Hub.<init>(Hub.java:99)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
	at java.util.Optional.map(Optional.java:215)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
Caused by: java.lang.ExceptionInInitializerError
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:100)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:87)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.openqa.grid.web.Hub.<init>(Hub.java:94)
	... 5 more
Caused by: java.lang.NullPointerException
	at java.util.TreeMap.putAll(TreeMap.java:313)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:426)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:63)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.deleteSeleniumPods(KubernetesContainerClient.java:392)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.initialiseContainerEnvironment(KubernetesContainerClient.java:338)
	at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:51)
	at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:61)
	... 13 more

**Comment by pearj** [comment]
@DeChrish the recommended way to use zalenium with kubernetes is to use helm now, see: https://opensource.zalando.com/zalenium/#kubernetes

**Comment by DeChrish** [comment]
@pearj Thanks. it is working.

I am using below command in docker implementation, how to configure the same  in kubernetes ?

docker run --rm -ti --name zalenium -p 4444:4444 -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY -e SAUCE_LABS_URL -v /tmp/videos:/home/seluser/videos -v /var/run/docker.sock:/var/run/docker.sock -e NEW_SESSION_WAIT_TIMEOUT=1800000 --privileged dosel/zalenium start --sauceLabsEnabled true
