### ISSUE TITLE
Error in RBAC Role definition in Helm Chart

### ISSUE THREAD

**Issue by snovikov** [zalando/zalenium#672]
I try to deploy Zalenium 3.13.0a with helm chart in kubernetes cluster.
Unfortunately it fails due to lack of permissions.
I run following:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl  create namespace zalenium
$ helm install \
  --name zalenium \
  --namespace zalenium \
  --set rbac.create=true \
  --set serviceAccount.create=true \
  --set hub.serviceType=LoadBalancer \
  local/zalenium
```

## Expected Behavior -
Pods are created, running and have status "ready".

## Actual Behavior -
Containers could not be started:
```
$ helm status zalenium
LAST DEPLOYED: Thu Jul 26 11:30:32 2018
NAMESPACE: zalenium
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/RoleBinding
NAME      AGE
zalenium  1m

==> v1/Service
NAME      TYPE          CLUSTER-IP     EXTERNAL-IP       PORT(S)         AGE
zalenium  LoadBalancer  100.70.226.89  a8ae7ff5f90b6...  4444:30589/TCP  1m

==> v1beta1/Deployment
NAME                   DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
zalenium-zalenium-hub  1        1        1           0          1m

==> v1/Pod(related)
NAME                                    READY  STATUS   RESTARTS  AGE
zalenium-zalenium-hub-694ccfffc9-znvls  0/1    Running  1         1m

==> v1/ServiceAccount
NAME      SECRETS  AGE
zalenium  1        1m

==> v1beta1/Role
NAME      AGE
zalenium  1m

$ kubectl --namespace=zalenium logs zalenium-zalenium-hub-694ccfffc9-znvls
Kubernetes service account found.
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
...........09:32:55.308 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.13.0', revision: 'unknown'
09:32:55.312 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
....09:32:56.597 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
....09:32:57.587 [main] WARN  d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://100.64.0.1/api/v1/namespaces/zalenium/pods/zalenium-zalenium-hub-694ccfffc9-znvls. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "zalenium-zalenium-hub-694ccfffc9-znvls" is forbidden: User "system:serviceaccount:zalenium:zalenium" cannot get pods in the namespace "zalenium".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:780)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:196)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:163)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:87)
	at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:35)
	at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:59)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:96)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:84)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.openqa.grid.web.Hub.<init>(Hub.java:93)
	at org.openqa.grid.selenium.GridLauncherV3$2.launch(GridLauncherV3.java:290)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:121)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:81)

```

**Comment by diemol** [comment]
Closed via #673
