### ISSUE TITLE
GridException "Error forwarding the new session request" on initiating a test on browserstack 

### ISSUE THREAD

**Issue by MilindThakur** [zalando/zalenium#695]
Zalenium Image Version(s):  
3.13.0b
Docker Version:  
17.09.1-ce
If using docker-compose, version:  
1.14.0
OS: 
16.04.1-Ubuntu
Docker Command to start Zalenium:  
```
version: '2.1'

services:
  #--------------#
      zalenium:
        image: "dosel/zalenium"
        container_name: zalenium
        hostname: zalenium
        privileged: true
        tty: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /tmp/videos:/home/seluser/videos
        ports:
          - 4444:4444
        command: >
          start --desiredContainers 1
                --maxDockerSeleniumContainers 10
                --screenWidth 1930 --screenHeight 1090
                --timeZone "Pacific/Auckland"
                --videoRecordingEnabled false
                --sauceLabsEnabled false
                --browserStackEnabled true
                --testingBotEnabled false
                --startTunnel true
                --seleniumImageName "elgalu/selenium"
                --sendAnonymousUsageInfo false
                --maxTestSessions 5
                --keepOnlyFailedTests true
                --debugEnabled false
        environment:
          - SAUCE_USERNAME
          - SAUCE_ACCESS_KEY
          - BROWSER_STACK_USER
          - BROWSER_STACK_KEY
          - TESTINGBOT_KEY
          - TESTINGBOT_SECRET
```

## Expected Behavior -
Should initiate tests on browserstack over a local tunnel

## Actual Behavior -
Get the following grid exception:
```
zalenium    | Docker version 17.09.1-ce, build 19e2cf6
zalenium    | -- LOG 09:36:11:146722401 Ensuring docker works...
zalenium    | -- LOG 09:36:11:183006995 Ensuring no stale Zalenium related containers are still around...
zalenium    | -- LOG 09:36:11:199786910 Ensuring docker-selenium is available...
zalenium    | haveged: haveged starting up
zalenium    | Copying files for Dashboard...
zalenium    | Starting Nginx reverse proxy...
zalenium    | Starting Selenium Hub...
.zalenium    | ...09:36:11.771 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.13.0', revision: 'unknown'
zalenium    | 09:36:11.774 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.zalenium    | .09:36:12.011 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
zalenium    | 09:36:12.011 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Autostarting container, because 0 is less than min 1
.zalenium    | .09:36:12.345 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
zalenium    | .09:36:12.407 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
zalenium    | 09:36:12.407 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.20.0.2:4445/grid/register/
zalenium    | 09:36:12.407 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.20.0.2:4445/wd/hub
.zalenium    | Selenium Hub started!
zalenium    | Sauce Labs not enabled...
zalenium    | Starting Browser Stack node...
..zalenium    | ...09:36:13.166 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.13.0', revision: 'unknown'
zalenium    | 09:36:13.172 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching a Selenium Grid node on port 30002
.zalenium    | 09:36:13.321 [main] INFO  o.o.s.remote.server.SeleniumServer - Selenium Server is up and running on port 30002
zalenium    | 09:36:13.321 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium Grid node is up and ready to register to the hub
zalenium    | 09:36:13.352 [main] INFO  o.o.g.i.utils.SelfRegisteringRemote - Registering the node to the hub: http://localhost:4444/grid/register
.....zalenium    | ......09:36:14.791 [qtp1564698139-15] INFO  d.z.e.z.p.BrowserStackRemoteProxy - [BS] Getting account max. concurrency from https://www.browserstack.com/automate/plan.json
zalenium    | 09:36:14.800 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_Q7du15] with dimensions [(1930, 1090)] and tz [sun.util.calendar.ZoneInfo[id="Pacific/Auckland",offset=43200000,dstSavings=3600000,useDaylight=true,transitions=156,lastRule=java.util.SimpleTimeZone[id=Pacific/Auckland,offset=43200000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=8,startDay=-1,startDayOfWeek=1,startTime=7200000,startTimeMode=1,endMode=3,endMonth=3,endDay=1,endDayOfWeek=1,endTime=7200000,endTimeMode=1]]].
zalenium    | 09:36:14.801 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_Q7du15, containerId=7e060ee94ed402659c6beb5b97b9a347a1cf75cbc19865adf5e5ce4fd41a29e7, nodePort=40000].
zalenium    | 09:36:14.802 [Thread-14] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://hub-cloud.browserstack.com:80
zalenium    | 09:36:14.847 [main] INFO  o.o.g.i.utils.SelfRegisteringRemote - The node is registered to the hub and ready to use
..zalenium    | Browser Stack node started!
zalenium    | Starting BrowserStackLocal...
zalenium    | Waiting for BrowserStack tunnel to start...
........zalenium    | ............09:36:17.542 [Thread-16] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.20.0.3:40000
zalenium    | 09:36:17.543 [Thread-16] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container 7e060ee94ed402659c6beb5b97b9a347a1cf75cbc19865adf5e5ce4fd41a29e7 http://172.20.0.3:40000.
..zalenium    | ..09:36:17.903 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_Q7du15 started after 3102.
....zalenium    | .....BrowserStack tunnel started! (wait-browserstack.sh)
zalenium    | TestingBot not enabled...
zalenium    | Zalenium is now ready!
+ echo 'Zalenium started! Ready to run some tests!'
Zalenium started! Ready to run some tests!
zalenium    | 09:36:32.630 [qtp1564698139-15] INFO  o.o.g.w.s.handler.RequestHandler - Got a request to create a new session: Capabilities {browserName: chrome, highlight: true, name: Can create an account succe..., platform: WINDOWS, version: }
zalenium    | 09:36:32.631 [qtp1564698139-15] INFO  d.z.e.z.registry.ZaleniumRegistry - Adding sessionRequest for {name=Can create an account successfully, browserName=chrome, highlight=true, version=, platform=WINDOWS}
zalenium    | 09:36:32.633 [Matcher thread] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Test will be forwarded to BrowserStack, {name=Can create an account successfully, browserName=chrome, highlight=true, version=, platform=WINDOWS}
zalenium    | 09:36:32.634 [Matcher thread] INFO  org.openqa.grid.internal.TestSlot - Trying to create a new session on test slot {browserName=BrowserStack, maxInstances=5, platformName=ANY}
zalenium    | 09:36:32.635 [Matcher thread] INFO  d.z.e.z.registry.ZaleniumRegistry - Test session with internal key 4a6a64b4-fc8c-4544-a769-d1885bf794da assigned to remote () after 0 seconds (36 ms).
zalenium    | 09:36:32.641 [Forwarding 4a6a64b4-fc8c-4544-a769-d1885bf794da (int. key, remote not contacted yet.) to http://hub-cloud.browserstack.com:80/wd/hub at 9:36:32 AM] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Currently using 1 parallel sessions towards BrowserStack. Attempt to start one more.
zalenium    | 09:36:32.655 [qtp1564698139-15] INFO  o.o.g.w.s.handler.RequestHandler - Error forwarding the new session new session request for webdriver should contain a location header or an 'application/json;charset=UTF-8' response body with the session ID.
zalenium    | org.openqa.grid.common.exception.GridException: new session request for webdriver should contain a location header or an 'application/json;charset=UTF-8' response body with the session ID.
zalenium    | 	at org.openqa.grid.internal.TestSession.updateHubIfNewWebDriverSession(TestSession.java:404)
zalenium    | 	at org.openqa.grid.internal.TestSession.forward(TestSession.java:248)
zalenium    | 	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:91)
zalenium    | 	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
zalenium    | 	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
zalenium    | 	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)
zalenium    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
zalenium    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
zalenium    | 	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
zalenium    | 	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
zalenium    | 	at io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:170)
zalenium    | 	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
zalenium    | 	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:533)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
zalenium    | 	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
zalenium    | 	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
zalenium    | 	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
zalenium    | 	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
zalenium    | 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
zalenium    | 	at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
zalenium    | 	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
zalenium    | 	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
zalenium    | 	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
zalenium    | 	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
zalenium    | 	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
zalenium    | 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
zalenium    | 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
zalenium    | 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
zalenium    | 	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
zalenium    | 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
zalenium    | 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
zalenium    | 	at java.lang.Thread.run(Thread.java:748)

```
The Zalenium container correctly shows the env variables for browseratck has been set.

Tried running an independent test targeting the browserstack hub url directly with credentials without zalenium and is working fine.

**Comment by diemol** [comment]
Hi @MilindThakur

Is this still happening, I was not able to reproduce. Besides, we run tests with BrowserStack as well in our CI and the error does not show up.

In case this is still happening, could you please help us to reproduce the issue?

**Comment by MilindThakur** [comment]
Hi @diemol 

I can still see that happening. Below is the command I use to start Zalenium with browserstack
```
$ docker run --rm -ti --name zalenium -p 4444:4444   -e BROWSER_STACK_USER -e BROWSER_STACK_KEY -e BROWSER_STACK_URL       -v /tmp/videos:/home/seluser/videos       -v /var/run/docker.sock:/var/run/docker.sock       --privileged dosel/zalenium start --browserStackEnabled true --startTunnel true
Docker version 17.09.1-ce, build 19e2cf6
-- LOG 21:53:20:153895173 Ensuring docker works...
-- LOG 21:53:20:225519752 Ensuring no stale Zalenium related containers are still around...
-- LOG 21:53:20:245007354 Ensuring docker-selenium is available...
haveged: haveged starting up
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
...21:53:20.852 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.14.0', revision: 'unknown'
21:53:20.855 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.21:53:21.085 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
21:53:21.086 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Autostarting container, because 0 is less than min 2
.21:53:21.416 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
21:53:21.466 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
21:53:21.466 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.17.0.2:4445/grid/register/
21:53:21.466 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.17.0.2:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Starting Browser Stack node...
...21:53:22.057 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.14.0', revision: 'unknown'
21:53:22.063 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching a Selenium Grid node on port 30002
.21:53:22.229 [main] INFO  o.o.s.remote.server.SeleniumServer - Selenium Server is up and running on port 30002
21:53:22.229 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium Grid node is up and ready to register to the hub
21:53:22.259 [main] INFO  o.o.g.i.utils.SelfRegisteringRemote - Registering the node to the hub: http://localhost:4444/grid/register
.....21:53:23.621 [qtp1564698139-25] INFO  d.z.e.z.p.BrowserStackRemoteProxy - [BS] Getting account max. concurrency from https://www.browserstack.com/automate/plan.json
21:53:23.631 [Thread-14] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://hub.browserstack.com:80
21:53:23.666 [main] INFO  o.o.g.i.utils.SelfRegisteringRemote - The node is registered to the hub and ready to use
21:53:23.707 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_bmuTPR] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
21:53:23.708 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_bmuTPR, containerId=dd86ab0cf80e7c72a0b8cbb896aa4c891188e033f6cfbaa3dc2986bf1f8b2e32, nodePort=40000].
Browser Stack node started!
Starting BrowserStackLocal...
Waiting for BrowserStack tunnel to start...
......21:53:25.496 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_fCFqN1] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
21:53:25.497 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_fCFqN1, containerId=144c12d5564a5c489ae65332831894e3ee2bcd13859bd26f91531174550de59a, nodePort=40001].
.....21:53:26.608 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_bmuTPR started after 2900.
21:53:26.689 [Thread-16] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.3:40000
21:53:26.689 [Thread-16] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container dd86ab0cf80e7c72a0b8cbb896aa4c891188e033f6cfbaa3dc2986bf1f8b2e32 http://172.17.0.3:40000.
.........21:53:28.345 [Thread-17] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.4:40001
21:53:28.346 [Thread-17] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container 144c12d5564a5c489ae65332831894e3ee2bcd13859bd26f91531174550de59a http://172.17.0.4:40001.
.21:53:28.666 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_fCFqN1 started after 3169.
.BrowserStack tunnel started! (wait-browserstack.sh)
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***********************************
```
Then I try to initialise webdriver using pythong bindings
```
>>> from selenium import webdriver
>>> desired_caps2 = {}
>>> desired_caps2['version'] = "ANY"
>>> desired_caps2['platform'] = "ANY"
>>> desired_caps2['browserName'] ="safari"
>>> driver = webdriver.Remote('http://localhost:4444/wd/hub', desired_caps2)
```
And I get following stacktrace from zalenium
```
21:57:31.199 [qtp1564698139-18] INFO  o.o.g.w.s.handler.RequestHandler - Got a request to create a new session: Capabilities {browserName: safari, version: ANY}
21:57:31.199 [qtp1564698139-18] INFO  d.z.e.z.registry.ZaleniumRegistry - Adding sessionRequest for {browserName=safari, version=ANY}
21:57:31.200 [Matcher thread] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Test will be forwarded to BrowserStack, {browserName=safari, version=ANY}
21:57:31.200 [Matcher thread] INFO  org.openqa.grid.internal.TestSlot - Trying to create a new session on test slot {browserName=BrowserStack, maxInstances=1, platformName=ANY}
21:57:31.200 [Matcher thread] INFO  d.z.e.z.registry.ZaleniumRegistry - Test session with internal key 50fd47a1-e1cd-4aa1-8698-7e318fd6c198 assigned to remote () after 0 seconds (4 ms).
21:57:31.203 [Forwarding 50fd47a1-e1cd-4aa1-8698-7e318fd6c198 (int. key, remote not contacted yet.) to http://hub.browserstack.com:80/wd/hub at 9:57:31 PM] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Currently using 1 parallel sessions towards BrowserStack. Attempt to start one more.
21:57:31.537 [qtp1564698139-18] INFO  o.o.g.w.s.handler.RequestHandler - Error forwarding the new session new session request for webdriver should contain a location header or an 'application/json;charset=UTF-8' response body with the session ID.
org.openqa.grid.common.exception.GridException: new session request for webdriver should contain a location header or an 'application/json;charset=UTF-8' response body with the session ID.
	at org.openqa.grid.internal.TestSession.updateHubIfNewWebDriverSession(TestSession.java:404)
	at org.openqa.grid.internal.TestSession.forward(TestSession.java:248)
	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:91)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:170)
	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
```
I can also see the browserstack tunnel has been started by the zalenium container:
```
$ docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                              NAMES
144c12d5564a        elgalu/selenium:latest   "entry.sh"               7 minutes ago       Up 7 minutes        40001/tcp, 50001/tcp               zalenium_fCFqN1
dd86ab0cf80e        elgalu/selenium:latest   "entry.sh"               7 minutes ago       Up 7 minutes        40000/tcp, 50000/tcp               zalenium_bmuTPR
1acb0d814783        dosel/zalenium           "entry.sh start --br…"   7 minutes ago       Up 7 minutes        0.0.0.0:4444->4444/tcp, 4445/tcp   zalenium
$ docker exec -ti 1acb0d814783 /bin/bash
seluser@1acb0d814783:~/logs$ cat browserstack-stdout.log 
BrowserStackLocal v7.1

Setting output as verbose
You can now access your local server(s) in our remote browser.


Connecting to BrowserStack using WebSocket protocol...
Platform supports WebSocket connections.

Press Ctrl-C to exit

```

**Comment by diemol** [comment]
I tried to reproduce again and I could not, the only thing I found was that if no platform and version is specified for Safari, sometimes it will timeout or produce unexpected results. So I used the following small script and it always work. (Using version 3.14.1 of the Python bindings).

```
from selenium import webdriver
desired_caps2 = {}
desired_caps2['version'] = "ANY"
desired_caps2['platform'] = "ANY"
desired_caps2['browserName'] ="safari"
desired_caps2['os_version']="High Sierra"
desired_caps2['browser_version']="11.0"
driver = webdriver.Remote('http://localhost:4444/wd/hub', desired_caps2)
driver.get("http://www.python.org")
driver.quit()
```

Whenever you can, please provide detailed instructions on how to reproduce it and reopen the issue. I spent a while and really could not make it fail the way you show it.
