### ISSUE TITLE
Zalenium Pod occasionally hang with Status: CrashLoopBackOff

### ISSUE THREAD

**Issue by CatCassie** [zalando/zalenium#720]
Zalenium Image Version(s):  
* zalenium image with latest tag

OS: 
Running kubectl on ubuntu linux.

If using Kubernetes, specify your environment, and if relevant your manifests:  
PKS (Pivotal Container Service) which is a pivotal flavor of kubernetes cluster. The manifest file will not be relevant with this particular issue.

## Expected Behavior -
Zalenium pod up and running.

## Actual Behavior -
Zalenium Pod occasionally hang with Status: CrashLoopBackOff. Sometimes the zalenium pods is up and running fine. We are able to go to the dashboard and see the videos we took from the tests. But other times the pods will hang at CrashLoopBackOff.  We did some investigation and below is the log we obtain from our k8s pod.

```
Kubernetes service account found.
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
..........21:04:52.712 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.14.0', revision: 'unknown'
21:04:52.717 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
....21:04:53.995 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
.21:04:54.293 [main] WARN  d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [zalenium-zalenium-pks-dumplings-6f5c95c9f7-64g8n]  in namespace: [zalenium-pks-eng]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:207)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:163)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:87)
	at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:35)
	at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:61)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:97)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:85)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.openqa.grid.web.Hub.<init>(Hub.java:94)
	at org.openqa.grid.selenium.GridLauncherV3$2.launch(GridLauncherV3.java:290)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:121)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:81)
Caused by: java.net.ConnectException: Failed to connect to /10.100.200.1:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:242)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:104)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:780)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:196)
	... 16 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
	... 48 common frames omitted
21:04:54.293 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - About to clean up any left over selenium pods created by Zalenium
Usage: <main class> [options]
  Options:
    --debug, -debug
      <Boolean> : enables LogLevel.FINE.
      Default: false
    --version, -version
      Displays the version and exits.
      Default: false
    -browserTimeout
      <Integer> in seconds : number of seconds a browser session is allowed to 
      hang while a WebDriver command is running (example: driver.get(url)). If 
      the timeout is reached while a WebDriver command is still processing, 
      the session will quit. Minimum value is 60. An unspecified, zero, or 
      negative value means wait indefinitely.
    -matcher, -capabilityMatcher
      <String> class name : a class implementing the CapabilityMatcher 
      interface. Specifies the logic the hub will follow to define whether a 
      request can be assigned to a node. For example, if you want to have the 
      matching process use regular expressions instead of exact match when 
      specifying browser version. ALL nodes of a grid ecosystem would then use 
      the same capabilityMatcher, as defined here.
    -cleanUpCycle
      <Integer> in ms : specifies how often the hub will poll running proxies 
      for timed-out (i.e. hung) threads. Must also specify "timeout" option
    -custom
      <String> : comma separated key=value pairs for custom grid extensions. 
      NOT RECOMMENDED -- may be deprecated in a future revision. Example: 
      -custom myParamA=Value1,myParamB=Value2
    -host
      <String> IP or hostname : usually determined automatically. Most 
      commonly useful in exotic network configurations (e.g. network with VPN)
      Default: 0.0.0.0
    -hubConfig
      <String> filename: a JSON file (following grid2 format), which defines 
      the hub properties
    -jettyThreads, -jettyMaxThreads
      <Integer> : max number of threads for Jetty. An unspecified, zero, or 
      negative value means the Jetty default value (200) will be used.
    -log
      <String> filename : the filename to use for logging. If omitted, will 
      log to STDOUT
    -maxSession
      <Integer> max number of tests that can run at the same time on the node, 
      irrespective of the browser used
    -newSessionWaitTimeout
      <Integer> in ms : The time after which a new test waiting for a node to 
      become available will time out. When that happens, the test will throw 
      an exception before attempting to start a browser. An unspecified, zero, 
      or negative value means wait indefinitely.
      Default: 600000
    -port
      <Integer> : the port number the server will use.
      Default: 4445
    -prioritizer
      <String> class name : a class implementing the Prioritizer interface. 
      Specify a custom Prioritizer if you want to sort the order in which new 
      session requests are processed when there is a queue. Default to null ( 
      no priority = FIFO )
    -registry
      <String> class name : a class implementing the GridRegistry interface. 
      Specifies the registry the hub will use.
      Default: de.zalando.ep.zalenium.registry.ZaleniumRegistry
    -role
      <String> options are [hub], [node], or [standalone].
      Default: hub
    -servlet, -servlets
      <String> : list of extra servlets the grid (hub or node) will make 
      available. Specify multiple on the command line: -servlet 
      tld.company.ServletA -servlet tld.company.ServletB. The servlet must 
      exist in the path: /grid/admin/ServletA /grid/admin/ServletB
    -timeout, -sessionTimeout
      <Integer> in seconds : Specifies the timeout before the server 
      automatically kills a session that hasn't had any activity in the last X 
      seconds. The test slot will then be released for another test to use. 
      This is typically used to take care of client crashes. For grid hub/node 
      roles, cleanUpCycle must also be set.
    -throwOnCapabilityNotPresent
      <Boolean> true or false : If true, the hub will reject all test requests 
      if no compatible proxy is currently registered. If set to false, the 
      request will queue until a node supporting the capability is registered 
      with the grid.
    -withoutServlet, -withoutServlets
      <String> : list of default (hub or node) servlets to disable. Advanced 
      use cases only. Not all default servlets can be disabled. Specify 
      multiple on the command line: -withoutServlet tld.company.ServletA 
      -withoutServlet tld.company.ServletB
org.openqa.grid.common.exception.GridConfigurationException: Error creating class with de.zalando.ep.zalenium.registry.ZaleniumRegistry : null
	at org.openqa.grid.web.Hub.<init>(Hub.java:98)
	at org.openqa.grid.selenium.GridLauncherV3$2.launch(GridLauncherV3.java:290)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:121)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:81)
Caused by: java.lang.ExceptionInInitializerError
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:97)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:85)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.openqa.grid.web.Hub.<init>(Hub.java:94)
	... 3 more
Caused by: java.lang.NullPointerException
	at java.util.TreeMap.putAll(TreeMap.java:313)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:412)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:49)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.deleteSeleniumPods(KubernetesContainerClient.java:393)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.initialiseContainerEnvironment(KubernetesContainerClient.java:339)
	at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:38)
	at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:61)
	... 11 more

```

* Note this line from the log: "Caused by: java.net.ConnectException: Failed to connect to /10.100.200.1:443", the address does not have a prefix such as https:// ... it just contains a forward slash

**Comment by pearj** [comment]
Sounds like 10.100.200.1:443 is your kubernetes master and it was offline when zalenium was starting. You can override the kubernetes master hostname with something else if there is a more reliable hostname for the kubernetes master. You should ask PKS support about this.

**Comment by pearj** [comment]
If they have multiple masters then it probably means they (PKS) were doing maintenance and the master was briefly down. From what I’ve heard kubernetes can take up to 14 seconds to fail over to another master.

**Comment by pearj** [comment]
To override the kubernetes hostname use the environment variable `KUBERNETES_MASTER` as seen at 
https://github.com/fabric8io/kubernetes-client

**Comment by diemol** [comment]
Closing due to inactivity.
