### ISSUE TITLE
Getting error while using maxDockerSeleniumContainers  to higher number

### ISSUE THREAD

**Issue by kunal-piplani** [zalando/zalenium#756]
error:-

rg.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request No route to host (Host unreachable)
Command duration or timeout: 12.08 seconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'chapdc3utrat10', ip: '10.131.112.29', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-754.3.5.el6.x86_64', java.version: '1.8.0_65'
Driver info: driver.version: RemoteWebDriver
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
        at org.tiaa.automation.util.RemoteBrowserFactory.getRemoteWebDriver(RemoteBrowserFactory.java:141)
        at org.tiaa.automation.util.RemoteBrowserFactory.getRemoteBrowser(RemoteBrowserFactory.java:82)
        at org.tiaa.automation.util.RemoteBrowserFactory.getRemoteBrowser(RemoteBrowserFactory.java:58)
        at org.tiaa.automation.test.Hooks.setWebDriver(Hooks.java:188)
        at org.tiaa.automation.test.Hooks.setWebDriver(Hooks.java:176)
        at stepDefinitions.BaseDefinition.before(BaseDefinition.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at cucumber.runtime.Utils$1.call(Utils.java:37)
        at cucumber.runtime.Timeout.timeout(Timeout.java:13)
        at cucumber.runtime.Utils.invoke(Utils.java:31)
        at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
        at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
        at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
        at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:201)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
        at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
        at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
        at cucumber.runtime.Runtime.run(Runtime.java:121)
        at cucumber.api.cli.Main.run(Main.java:36)
        at cucumber.api.cli.Main.main(Main.java:18)
Caused by: org.openqa.grid.common.exception.GridException: Error forwarding the new session Error forwarding the request No route to host (Host unreachable)
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:118)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:170)
        at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:748)

query:-
also juut want to know that what is the difference between maxdockerSeleniumContainer and desiredcontainer ?

I want to run 50 test case in parallel and our framework  is like using gradle task to run the testcases in parallel on feature level  so there are total 50 feature file .

I used command

node_ip=$(echo 172.17.0.{1..256} | sed 's/ /,/g')

sudo docker run --rm -ti --name zalenium -p 4444:4444 \

-v /var/run/docker.sock:/var/run/docker.sock \

-v /tmp/videos:/home/seluser/videos \

-e SAUCE_USERNAME -e SAUCE_ACCESS_KEY -e SAUCE_LABS_URL \

-e "zalenium_https_proxy=http://proxy.ops.xxx-xx.org:8080" \

-e "zalenium_http_proxy=http://proxy.ops.xxxx-xx.org:8080" \

-e "zalenium_no_proxy=localhost,127.0.0.1,cloud.xxxx.org,"${node_ip} \

-e ZALENIUM_EXTRA_JVM_PARAMS='-Dwebdriver.http.factory=apache -Dhttps.proxyHost=proxy.ops.xxxx.org -Dhttps.proxyPort=8080' \

--privileged dosel/zalenium start --sauceLabsEnabled false --maxTestSessions 900 --desiredContainers 50  --maxDockerSeleniumContainers 50  

OS:-

  |  
-- | --
Type | Virtual Machine
Description | Red Hat Linux 7 OS
Interface type | vSphere (vCenter)
CPUs | 6
Memory | 65,536 MB
Storage | 50 GB
Disk Volume
Disk label | Hard disk 1
Disk input id | DISK_INPUT_ID1
Disk capacity | 50 GB
Network
Network name | VB_T3_Guest_3252
  |  
IP | 10.xxx.xxxx.xxx
Expected behavior :- it should run all test casesActual behavior :- failing as mentioned above . Steps to reproduce : run Zalenium with 50+ test cases in parallel using command that I have mentioned | .

**Comment by diemol** [comment]
Hi @kunal-piplani,

From the stacktrace it looks like one of the nodes died. This makes sense since you are trying to run 50 tests with video on 50 containers concurrently in a machine that only has 6 CPUs available. Rule of thumb, per container: 1 CPU, 1GB RAM, if video enabled 1 CPU more.

Please start with a lower number and find the spot where your tests are stable with a given number of concurrent tests and containers. If you need some guidance, you could check https://github.com/zalando/zalenium/blob/master/docs/performance.md.

Feel free to reopen if you have errors after adjusting the number of containers to the available CPUs.
