### ISSUE TITLE
Error when setting zaleniumMessage cookie with # in the string

### ISSUE THREAD

**Issue by manevpe** [zalando/zalenium#763]
Zalenium Image Version(s):  
3.14.0g (Latest)
Docker Version:  
18.05.0-ce

OS: 
Centos7

Using Kubernetes:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "25"
  creationTimestamp: 2018-10-22T12:44:53Z
  generation: 25
  labels:
    app: zalenium
    role: grid
  name: zalenium
  namespace: zalenium
  resourceVersion: "2046797"
  selfLink: /apis/apps/v1/namespaces/zalenium/deployments/zalenium
  uid: 45d11f34-d5f8-11e8-b5b1-005056b77303
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zalenium
      role: grid
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zalenium
        role: grid
    spec:
      containers:
      - args:
        - start
        - --desiredContainers
        - "3"
        - --screenWidth
        - "1920"
        - --screenHeight
        - "1080"
        - --seleniumImageName
        - elgalu/selenium
        - --maxTestSessions
        - "1"
        - --maxDockerSeleniumContainers
        - "4"
        env:
        - name: ZALENIUM_KUBERNETES_CPU_REQUEST
          value: 250m
        - name: ZALENIUM_KUBERNETES_CPU_LIMIT
          value: 2000m
        - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
          value: 500Mi
        - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
          value: 2Gi
        - name: OVERRIDE_WAIT_TIME
          value: 5m
        - name: ZALENIUM_EXTRA_JVM_PARAMS
          value: -Dwebdriver.http.factory=apache
        image: dosel/zalenium:latest
        imagePullPolicy: Always
        name: zalenium
        ports:
        - containerPort: 4444
          protocol: TCP
        resources:
          requests:
            cpu: 333m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/seluser/videos
          name: zalenium-data
        - mountPath: /tmp/mounted
          name: zalenium-mounted
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zalenium
      serviceAccountName: zalenium
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: zalenium-data
      - emptyDir: {}
        name: zalenium-mounted
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-22T12:44:53Z
    lastUpdateTime: 2018-10-22T12:44:53Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 25
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

## Actual Behavior
We see a lot of the following errors:
org.openqa.selenium.WebDriverException: The following error occurred: Session [cbdb3deb0f11f01891226058b7ffca22] was terminated due to FORWARDING_TO_NODE_FAILED
OR
[main] WARN net.thucydides.core.webdriver.WebDriverFacade - Error while quitting the driver (Session [cbdb3deb0f11f01891226058b7ffca22] was terminated due to FORWARDING_TO_NODE_FAILED

They usually happen in the middle of a test or when quiting a test.

The logs from the zalenium container:
```
10:00:37.742 [OkHttp https://10.96.0.1/...] ERROR i.f.k.c.d.i.ExecWebSocketListener - Exec Failure: HTTP:400. Message:you must specify at least 1 of stdin, stdout, stderr
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:228)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:195)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
10:00:37.742 [OkHttp https://10.96.0.1/...] ERROR d.z.e.z.c.k.KubernetesContainerClient - zalenium-40000-kmzgm Failed to execute command [bash, -c, notify 'Zalenium', 'Get action task by name: QAAUI-185-1541581220439#andras', --icon=/home/seluser/images/message.png]
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:228)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:195)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
10:00:37.743 [qtp221861886-38] ERROR o.o.g.w.s.handler.RequestHandler - cannot forward the request you must specify at least 1 of stdin, stdout, stderr
io.fabric8.kubernetes.client.KubernetesClientException: you must specify at least 1 of stdin, stdout, stderr
        at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.onFailure(ExecWebSocketListener.java:228)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:197)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

We have tried with the ZALENIUM_EXTRA_JVM_PARAMS=-Dwebdriver.http.factory=apache and without it - the issue is reproducible in both cases.
We have also tried increasing the maxTestSessions, but it did not help as well

## Expected Behavior -
No connection errors during test execution.

**Comment by manevpe** [comment]
Hi @diemol and thanks for looking into this.
We have k8s 1.12.1 - the linked issue should have been fixed long before that, so I'm not sure it is the same one.
We have setup the env to use the apache http client, but it is seems the errors are comming from okhttp - any suggestions?

**Comment by manevpe** [comment]
I've investigated this some more and I found that it is happening only when the annotations in the video are enabled (i.e. setting the zaleniumMessage cookie).
Turning them off and the errors disappear.
Same code to set the cookie works in some cases, but fails in others.
And the failure / exception is observed on the very next browser action.

**Comment by diemol** [comment]
@manevpe can you post a sample value for the cookie when it contains a "#"?
I tried with a simple "Hi there! #sayingHi" message but I didn't get any error.

Nevertheless, we need to add a try - catch in that code block, if something breaks there, the whole session could crash.

**Comment by manevpe** [comment]
@diemol the value that break it for us is "Create action task automation#1234-5678-9012-3456 {}".
But notice that the exception is actually seen on the next browser action.

**Comment by diemol** [comment]
That's strange, I just executed a test using that message and it worked. I executed an additional action after setting the message.

![zalenium_loadtheinternetpageandchecktitle_chrome_l](https://user-images.githubusercontent.com/5992658/49211062-fdab5500-f3be-11e8-9ef2-030d26ad7cb7.gif)

**Comment by diemol** [comment]
Ah, you are using k8s, maybe something is not working there. We will check with MiniKube

**Comment by diemol** [comment]
OK, I was able to reproduce it with Minikube, no clue why it happens, we will check if there is something that can be done. Or we could end up removing the "#" from the message.

**Comment by manevpe** [comment]
Glad to hear you were able to reproduce it.
We have workarounded it exactly like that.
Its not an issue for us anymore, but other people might hit the same problem and wonder why, as it is hard to debug.

**Comment by diemol** [comment]
I could not really pinpoint the root cause but indeed removing the `#` avoids the error. Somehow it always fails in Travis but I can see locally how it works by removing it.
We will push this fix to master and release in some days.

Thank you for taking the time to debug this issue and helping us to fix it by diagnosing it.
