### ISSUE TITLE
How to pass screen resolution for each newly created container

### ISSUE THREAD

**Issue by umedyohanan** [zalando/zalenium#790]
Zalenium Image Version(s):  
3.141.59d
Docker Version:  
18.09.0
OS: 
Ubuntu 16.04
Docker Command to start Zalenium:  
```bash
docker run --rm -ti --name zalenium -p 4444:4444 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium \
start --desiredContainers 0 --maxTestSessions 2
```
The test is executed using remote webdriver with capabilities:

```python
 self.capabilities = {
                "browserName":"firefox",
                "maxInstances":"1",
                "platform":"LINUX",
                "platformName":"LINUX",
                "seleniumProtocol":"WebDriver",
                "version":"63.0.3",
                "acceptInsecureCerts": True
            }

self.driver = webdriver.Remote(command_executor=self.selenium_url,
                                           desired_capabilities=self.capabilities,
                                           browser_profile=self.profile)
```

## Expected Behavior -
As described on #586 above command should be the way to execute the test with different resolutions for each instance. 
## Actual Behavior -
Since there isn't any running node I get the exception from hub:
```log
INFO  o.o.g.w.s.handler.RequestHandler - Error forwarding the new session Empty pool of VM for setup Capabilities {acceptInsecureCerts: true, browserName: firefox, maxInstances: 1, platform: LINUX, platformName: linux, seleniumProtocol: WebDriver, version: 63.0.3}
org.openqa.grid.common.exception.GridException: Empty pool of VM for setup Capabilities {acceptInsecureCerts: true, browserName: firefox, maxInstances: 1, platform: LINUX, platformName: linux, seleniumProtocol: WebDriver, version: 63.0.3}
        at org.openqa.grid.internal.ProxySet.verifyAbilityToHandleDesiredCapabilities(ProxySet.java:146)
        at de.zalando.ep.zalenium.proxy.AutoStartProxySet.verifyAbilityToHandleDesiredCapabilities(AutoStartProxySet.java:191)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.addNewSessionRequest(ZaleniumRegistry.java:257)
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:111)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
        at io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:170)
        at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
```

What am I doing wrong? Is there any way to pass the screen resolution before each test execution?

**Comment by diemol** [comment]
Hi @umedyohanan,

To set a screen resolution per test (copying the Java example from the docs).

```
    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.FIREFOX);
    desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.LINUX);
    desiredCapabilities.setCapability("screenResolution", "1280x720");
``` 

About the error you are getting, it is because you are starting with `--desiredContainers 0`, so no nodes have registered to the hub, and therefore it does not know the browserVersion that is available. So just remove the `version":"63.0.3"` part, and it will work.

Feel free to reopen in case something else pops up.
