### ISSUE TITLE
Zalenium - Forbidden! Service account doesn't have access.

### ISSUE THREAD

**Issue by hajtomoto** [zalando/zalenium#792]
Hi

I cannot start Zalenium on Azure Kubernetes.
I tried your tutorial using helm:
downloaded all the files and charts to local repo,
executed helm install local/Zalenium

all installed but Zalenium endup in CrashLoopBackOff

maybe I messed up my accouts on kubernetes?
I executed following commands to allow helm/tiller install Zalenium:   (helm 2.11)

$>kubectl create serviceaccount --namespace kube-system tiller
$>kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
$>helm init --service-account tiller

honest-worm-zalenium-c87498498-b4kzq 

format_color_text text_fields timer_off refresh 

exposure_zero file_download 

Kubernetes service account found. 
Copying files for Dashboard... 
Starting Nginx reverse proxy... 
Starting Selenium Hub... 
........10:34:43.825 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown 
..10:34:44.322 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445 
...10:34:45.615 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support 
....10:34:46.701 [main] WARN  d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support. 
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://luk8cluste-luk8s-7f2a24-ae78ff42.hcp.westeurope.azmk8s.io/api/v1/namespaces/default/pods/honest-worm-zalenium-c87498498-b4kzq. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "honest-worm-zalenium-c87498498-b4kzq" is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default". 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:476) 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:413) 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313) 
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296) 
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:794) 
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:210) 
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177) 
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:90) 
	at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:48) 
	at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22) 
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:61) 
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:100) 
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:87) 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
	at java.lang.Class.newInstance(Class.java:442) 
	at org.openqa.grid.web.Hub.<init>(Hub.java:94) 
	at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264) 
	at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86) 
	at java.util.Optional.map(Optional.java:215) 
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86) 
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70) 
10:34:46.701 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - About to clean up any left over selenium pods created by Zalenium

**Comment by diemol** [comment]
Hi @hajtomoto,

The error is clear `User "system:serviceaccount:default:default" cannot get pods in the namespace "default".`. Somehow the config you are using is not the correct one. 

Thanks to @arnaud-deprez, the Kubernetes docs have been updated recently, have a look at them, and try the helm chart from the docs. 

If you need more help, feel free to join us at the #zalenium channel at [Slack](https://seleniumhq.herokuapp.com).
