### ISSUE TITLE
PKIX path validation failed after trying to create a Zalenium deployment in Kubernetes 

### ISSUE THREAD

**Issue by RaoneCosta** [zalando/zalenium#835]
Hi folks. I would like to have zalenium containers running in Kubernetes in order to execute my automated test scripts.
However, I am facing an error, which is impacting the pod creation.

**Kubernetes**

kubectl create -f zalenium-deployment.yaml

kubectl logs zalenium-84cfc866bd-dgznb
_Kubernetes service account found.
haveged: haveged starting up
Copying files for Dashboard...
cp: cannot create regular file '/home/seluser/videos/index.html': Permission denied
cp: cannot create directory '/home/seluser/videos/css': Permission denied
cp: cannot create directory '/home/seluser/videos/js': Permission denied
Starting Nginx reverse proxy...
Starting Selenium Hub...
...13:47:32.160 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
.13:47:32.278 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.13:47:32.581 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
13:47:32.645 [main] WARN  d.z.e.z.c.k.KubernetesContainerClient - Error initialising Kubernetes support.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [zalenium]  in namespace: [gcc-qe]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:221)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177)
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:90)
        at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:43)
        at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
        at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:62)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:101)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:87)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.openqa.grid.web.Hub.<init>(Hub.java:94)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
        at java.util.Optional.map(Optional.java:215)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:318)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:282)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:66)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:107)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:794)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:210)
        ... 18 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:259)
        at sun.security.validator.Validator.validate(Validator.java:262)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
        ... 59 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:154)
        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357)
        ... 65 common frames omitted
13:47:32.646 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - About to clean up any left over docker-selenium pods created by Zalenium
Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Error creating class with de.zalando.ep.zalenium.registry.ZaleniumRegistry : null
        at org.openqa.grid.web.Hub.<init>(Hub.java:99)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
        at java.util.Optional.map(Optional.java:215)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
Caused by: java.lang.ExceptionInInitializerError
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:101)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:87)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.openqa.grid.web.Hub.<init>(Hub.java:94)
        ... 5 more
Caused by: java.lang.NullPointerException
        at java.util.TreeMap.putAll(TreeMap.java:313)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:426)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:63)
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.deleteSeleniumPods(KubernetesContainerClient.java:392)
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.initialiseContainerEnvironment(KubernetesContainerClient.java:338)
        at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:46)
        at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
        at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:62)
        ... 13 more_

Causing **Back-off restarting failed container** error

**Zalenium Image Version(s):**  
latest
**Docker Version:**  
17.09.0-ce

**OS:** 
Windows 10

**My deployment file:**
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f zalenium-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: zalenium
  name: zalenium
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zalenium
    spec:
      containers:
      - args:
        - start
        - --desiredContainers
        - "2"
        - --maxDockerSeleniumContainers
        - "8"
        - --screenWidth
        - "1920"
        - --screenHeight
        - "1080"
        - --timeZone
        - America/Sao_Paulo
        - --videoRecordingEnabled
        - "false"
        - --sauceLabsEnabled
        - "false"
        - --browserStackEnabled
        - "false"
        - --testingBotEnabled
        - "false"
        - --startTunnel
        - "false"
        - --maxTestSessions
        - "1"
        image: harbor.ausmpc.pcf.dell.com/gcc-qe/zalenium
        name: zalenium
        ports:
        - containerPort: 4444
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /home/seluser/videos
          name: zalenium-claim0
        - mountPath: /var/run/docker.sock
          name: zalenium-claim1
      hostname: zalenium
      restartPolicy: Always
      volumes:
      - name: zalenium-claim0
        persistentVolumeClaim:
          claimName: zalenium-claim0
      - name: zalenium-claim1
        persistentVolumeClaim:
          claimName: zalenium-claim1
status: {}

It seems something related to certification missing. Do you have any idea how I can solve it?

**Comment by diemol** [comment]
Hi @RaoneCosta,

It seems that the role does not have enough permissions. To avoid all that, you should deploy using the helm chart, which is the recommended way to do it.

Give it a try and let us know how it went.

**Comment by RaoneCosta** [comment]
Hi Diemol,

Thanks for your quick response.
We have tried with Helm. Unfortunately, same issue.

Attaching Log.
[zalenium_logs.txt](https://github.com/zalando/zalenium/files/2761062/zalenium_logs.txt)

**Comment by diemol** [comment]
Hey @RaoneCosta,

I checked the log, and it just seems that there is something wrong in the certificates of your environment. Basically Zalenium tries to create the pod:
```
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [zalenium-78fdb9bd47-j5b7l]  in namespace: [zalenium]  failed.
```
because of that PKIX exception, which after googling it, it points to some certificates not being trusted by Java or just being invaling. Could you please check that first? There is not much we can do on our side.

**Comment by RaoneCosta** [comment]
Hi Diemol,

Yes, this is our guess as well. 
We are in touch with the team who provided us the kubernetes cluster. They are verifying in their side.

Any news, I will let you know. Thanks for your time.

**Comment by diemol** [comment]
Sounds good @RaoneCosta.

If there is something else we can help with, let us know. 
Closing thins for now.

**Comment by ibmdcb** [comment]
Actually, according to https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/, the cert Zalenium needs to trust is automatically mounted into a pod at “/var/run/secrets/kubernetes.io/serviceaccount/ca.crt“. 

Zalenium needs to implement Java switches to trust that cert.

**Comment by diemol** [comment]
A simpler option would be to create your own custom Zalenium image where you add this certificate and trust it.

**Comment by ibmdcb** [comment]
The cert used by our kubernetes's API server was a self-signed cert automatically generated by an automation tool during cluster creation. So each cluster has its own cert, but different ones. There must be other Kubernetes providers that do the same. But we can wait and see if others request the same.

Thanks.
