### ISSUE TITLE
Getting error while starting Zalenium hub on GKE

### ISSUE THREAD

**Issue by anirudhkumarvyas** [zalando/zalenium#843]
## 💥 Regression Report

I am a newbie and trying out Zalenium. I had setup Zalenium in Google Container Engine end of december by following up the instructions on your website and all was working fine. I wanted to change/scale up the configuration so deleted the existing cluster and tried to recreate it but every time my pods do not start and I am getting below error:
[null__logs__2019-01-20T01-12.txt](https://github.com/zalando/zalenium/files/2776498/null__logs__2019-01-20T01-12.txt)

```
2019-01-20 01:07:50.000 GMT
Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Error creating class with de.zalando.ep.zalenium.registry.ZaleniumRegistry : null at org.openqa.grid.web.Hub.(Hub.java:99) at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264) at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86) at java.util.Optional.map(Optional.java:215) at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86) at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70) Caused by: java.lang.ExceptionInInitializerError at de.zalando.ep.zalenium.registry.ZaleniumRegistry.(ZaleniumRegistry.java:102) at de.zalando.ep.zalenium.registry.ZaleniumRegistry.(ZaleniumRegistry.java:88) at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at java.lang.Class.newInstance(Class.java:442) at org.openqa.grid.web.Hub.(Hub.java:94) ... 5 more Caused by: java.lang.NullPointerException at java.util.TreeMap.putAll(TreeMap.java:313) at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:426) at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:63) at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.deleteSeleniumPods(KubernetesContainerClient.java:392) at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.initialiseContainerEnvironment(KubernetesContainerClient.java:338) at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:46) at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22) at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.(DockeredSeleniumStarter.java:63) ... 13 more
```

## Last working version

Worked up to version:3.141.59e

Stopped working in version:3.141.59g

## To Reproduce

Followed the instruction for setting up zalenium Google Container Engine (GKE) on : 
https://opensource.zalando.com/zalenium/ 

Please find my yaml files attached
[pv.yaml.txt](https://github.com/zalando/zalenium/files/2776479/pv.yaml.txt)
[plumbing.yaml.txt](https://github.com/zalando/zalenium/files/2776480/plumbing.yaml.txt)
[zalenium.yaml.txt](https://github.com/zalando/zalenium/files/2776481/zalenium.yaml.txt)

## Expected behavior

Pods should start and should be able to run the test

## Test script reproducing this issue (when applicable)

N/A

## Environment

OS: linux
Zalenium Image Version(s): 3.141.59g

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

gcloud version
Google Cloud SDK 230.0.0
bq 2.0.39
core 2019.01.11
gsutil 4.35
kubectl 2018.09.17

**Comment by diemol** [comment]
@anirudhkumarvyas seems something changed in your cluster, the account doesn't have the needed permissions. You can see that in the log:

```
    "textPayload": "io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.43.240.1/api/v1/namespaces/zalenium/pods/zalenium-58d6c9649b-4tg89. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods \"zalenium-58d6c9649b-4tg89\" is forbidden: User \"system:serviceaccount:zalenium:zalenium\" cannot get pods in the namespace \"zalenium\".\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:476)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:413)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:794)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:210)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177)\n\tat de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:90)\n\tat de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:43)\n\tat de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)\n\tat de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.<clinit>(DockeredSeleniumStarter.java:63)\n\tat de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:102)\n\tat de.zalando.ep.zalenium.registry.ZaleniumRegistry.<init>(ZaleniumRegistry.java:88)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat java.lang.Class.newInstance(Class.java:442)\n\tat org.openqa.grid.web.Hub.<init>(Hub.java:94)\n\tat org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:264)\n\tat org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)\n\tat java.util.Optional.map(Optional.java:215)\n\tat org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)\n\tat org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)\n",
```

Also, since a few weeks ago, the recommended way to deploy is using helm, so please have a look.

Feel free to reopen in case the issue is related to Zalenium, for additional help, we recommend asking questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y) where the community can help you as well.
