### ISSUE TITLE
unable to start the nodes

### ISSUE THREAD

**Issue by kothaSravanthi** [zalando/zalenium#865]
Hi,

I am  new to Zalenium, I am using the following cmd to start the Zalenium:

docker run --rm -ti --name zalenium -p 4444:4444 -e ZALENIUM_EXTRA_JVM_PARAMS="-Dwebdriver.http.factory=apache" -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start --sauceLabsEnabled false --seleniumImageName elgalu/selenium:2.53.1z --debugEnabled true --desiredContainers 4

Once I ran the above cmd, them am getting the following error in the terminal:
[AutoStartProxyPoolPoller] DEBUG d.z.e.z.c.DockerContainerClient - Error while getting node status, probably the node is still starting up...
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.URL.openStream(URL.java:1045)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1153)
	at de.zalando.ep.zalenium.container.DockerContainerClient.isReady(DockerContainerClient.java:643)
	at de.zalando.ep.zalenium.proxy.DockeredSeleniumStarter.containerHasStarted(DockeredSeleniumStarter.java:325)
	at de.zalando.ep.zalenium.proxy.AutoStartProxySet.checkContainers(AutoStartProxySet.java:392)
	at de.zalando.ep.zalenium.proxy.AutoStartProxySet.lambda$0(AutoStartProxySet.java:124)
	at java.lang.Thread.run(Thread.java:748)
13:04:07.986 [AutoStartProxyPoolPoller] DEBUG d.z.e.z.proxy.AutoStartProxySet - 0 proxies are idle and will be removed.
13:04:07.986 [AutoStartProxyPoolPoller] DEBUG d.z.e.z.proxy.AutoStartProxySet - Checked containers.

![image](https://user-images.githubusercontent.com/47561844/52634745-04416700-2eee-11e9-9466-837a02d38285.png)

Can you please help in starting the Zalenium with lowest version.

the above error is not stopping at all, May be Zalenium is polling to create minimum no. of node to get ready.

**Comment by kothaSravanthi** [comment]
Am running on :  
Docker :18.09.2, build 6247962 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by diemol** [comment]
Hi @kothaSravanthi,

You are using an old image `elgalu/selenium:2.53.1z` with the latest Zalenium, which is not supported. You would need to find an old Zalenium release that works with that image.

**Comment by kothaSravanthi** [comment]
@diemol , Thanks for your immediate response. Please help me the supported Zalenium release for elgalu/selenium:2.53.1z.

**Comment by kothaSravanthi** [comment]
Found it!!!

**Comment by diemol** [comment]
They start with 2.53.1, please go through the releases to find it.
Just keep in mind that the 2.x releases are no longer supported.

**Comment by kothaSravanthi** [comment]
@diemol ,Thanks!!!
