### ISSUE TITLE
RemoteDashboard Sending Logs Error when specify Capability "build"

### ISSUE THREAD

**Issue by jayjay021** [zalando/zalenium#868]
## 🐛 Bug Report

When using the DesiredCapability "build-tag" the path for selenium-multinode-stderr.log and firefox_driver.log is incorrect:

```
java.io.FileNotFoundException: /home/seluser/videos/myTestBuild/logs/myTest_20190216202813565_COMPLETED/firefox_driver.log (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at de.zalando.ep.zalenium.dashboard.remote.RemoteDriverLogDashboard.updateDashboard(RemoteDriverLogDashboard.java:25)
        at de.zalando.ep.zalenium.dashboard.DashboardCollection.updateDashboard(DashboardCollection.java:59)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.cleanupNode(DockerSeleniumRemoteProxy.java:755)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.afterSession(DockerSeleniumRemoteProxy.java:398)
        at org.openqa.grid.internal.TestSlot.performAfterSessionEvent(TestSlot.java:253)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry._release(ZaleniumRegistry.java:198)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.lambda$0(ZaleniumRegistry.java:182)
        at java.lang.Thread.run(Thread.java:748)
20:28:26.518 [http://172.17.0.23:40001] WARN  d.z.e.z.d.DashboardCollection - Error during update of dashboard:
java.io.FileNotFoundException: /home/seluser/videos/myTestBuild/logs/myTest_20190216202813565_COMPLETED/selenium-multinode-stderr.log (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at de.zalando.ep.zalenium.dashboard.remote.RemoteSeleniumLogDashboard.updateDashboard(RemoteSeleniumLogDashboard.java:25)
        at de.zalando.ep.zalenium.dashboard.DashboardCollection.updateDashboard(DashboardCollection.java:59)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.cleanupNode(DockerSeleniumRemoteProxy.java:755)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.afterSession(DockerSeleniumRemoteProxy.java:398)
        at org.openqa.grid.internal.TestSlot.performAfterSessionEvent(TestSlot.java:253)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry._release(ZaleniumRegistry.java:198)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.lambda$0(ZaleniumRegistry.java:182)
        at java.lang.Thread.run(Thread.java:748)
```

As you can see above the search-path for the logs is:
/home/seluser/videos/**myTestBuild**/**logs**/myTest_20190216202813565_COMPLETED/selenium-multinode-stderr.log

the correct one would be:
/home/seluser/videos/**logs**/**myTestBuild**/myTest_20190216202813565_COMPLETED/selenium-multinode-stderr.log

same for firefox_driver.log

Java code:
`    public static void main (String[] args) throws Exception{

        DesiredCapabilities cap = DesiredCapabilities.firefox();
        cap.setCapability("name", "myTestName");
        cap.setCapability("build", "myTestBuild");
        cap.setCapability("testFileNameTemplate", "myTest_{timestamp}_{testStatus}");
        WebDriver driver;
        driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), cap);
        driver.get("http://www.google.de");
        String titel = driver.getTitle();
        System.out.println(titel);
        driver.quit();
    }`

## Environment

OS: Ubuntu 16.04.3 LTS
Zalenium Image Version(s): dosel/zalenium:latest
Docker version: 18.09.0

docker run --rm -ti --name zalenium -p 4444:4444 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /tmp/videos:/home/seluser/videos  \
-e REMOTE_DASHBOARD_HOST="http://localhost:4000" \
--privileged dosel/zalenium start

**Comment by diemol** [comment]
Fix merged into master, will release tomorrow.
