### ISSUE TITLE
Couldn't connect to selenium server - Jenkins Container to Zalenium Container

### ISSUE THREAD

**Issue by guptapranay** [zalando/zalenium#877]
I am trying to connect to Zalenium docker through Jenkins Job (Jenkins container). 

But my Jenkins job fails because of error: Couldn't connect to selenium server.

ERROR: Couldn't connect to selenium server
chrome
    at new RuntimeError (/var/jenkins_home/workspace/zalenium-test/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/var/jenkins_home/workspace/zalenium-test/node_modules/webdriverio/build/lib/utils/RequestHandler.js:264:37)
    at self.callback (/var/jenkins_home/workspace/zalenium-test/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/var/jenkins_home/workspace/zalenium-test/node_modules/webdriverio/node_modules/request/request.js:971:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:324:9)
    at emitOne (events.js:96:13)

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we didn't get more info.
