### ISSUE TITLE
Manage saucelabs Europe

### ISSUE THREAD

**Issue by romainlouvet** [zalando/zalenium#903]
## 🐛 Bug Report

14:26:40.123 [SauceLabs addTestToDashboard seleniumSessionId [6b9b14f36f9e4d39b02ac224cb779a0b] testCompleted [true]] ERROR d.z.e.z.util.CommonProxyUtilities - java.io.FileNotFoundException: https://saucelabs.com/rest/v1/rlouvet/jobs/6b9b14f36f9e4d39b02ac224cb779a0b
java.io.FileNotFoundException: https://saucelabs.com/rest/v1/rlouvet/jobs/6b9b14f36f9e4d39b02ac224cb779a0b

because my vm is in EU DataCenter https://wiki.saucelabs.com/display/DOCS/Sauce+Labs+European+Data+Center+Configuration+Information

**Comment by diemol** [comment]
@romainlouvet
You can pass the Sauce Labs endpoint url via an env var: `SAUCE_LABS_URL`, and there just put https://ondemand.eu-central-1.saucelabs.com/wd/hub.

**Comment by romainlouvet** [comment]
if I set SAUCE_LABS_URL=https://ondemand.eu-central-1.saucelabs.com
I have alwayd 13:01:40.686 [SauceLabs addTestToDashboard seleniumSessionId [0010cfc780df49a8a3d71f4fce68ca7f] testCompleted [true]] ERROR d.z.e.z.util.CommonProxyUtilities - java.io.FileNotFoundException: https://saucelabs.com/rest/v1/rlouvet/jobs/0010cfc780df49a8a3d71f4fce68ca7f
java.io.FileNotFoundException: https://saucelabs.com/rest/v1/rlouvet/jobs/0010cfc780df49a8a3d71f4fce68ca7f
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at de.zalando.ep.zalenium.util.CommonProxyUtilities.readJSONFromUrl(CommonProxyUtilities.java:53)
	at de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy.getTestInformation(SauceLabsRemoteProxy.java:106)
	at de.zalando.ep.zalenium.proxy.CloudTestingRemoteProxy.lambda$0(CloudTestingRemoteProxy.java:272)
	at java.lang.Thread.run(Thread.java:748)
13:01:40.693 [SauceLabs addTestToDashboard seleniumSessionId [0010cfc780df49a8a3d71f4fce68ca7f] testCompleted [true]] ERROR d.z.e.z.util.CommonProxyUtilities - java.io.FileNotFoundException: https://saucelabs.com/rest/v1/rlouvet/jobs/0010cfc780df49a8a3d71f4fce68ca7f
java.io.FileNotFoundException: https://saucelabs.com/rest/v1/rlouvet/jobs/0010cfc780df49a8a3d71f4fce68ca7f
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at de.zalando.ep.zalenium.util.CommonProxyUtilities.readJSONFromUrl(CommonProxyUtilities.java:53)
	at de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy.getTestInformation(SauceLabsRemoteProxy.java:106)
	at de.zalando.ep.zalenium.proxy.CloudTestingRemoteProxy.lambda$0(CloudTestingRemoteProxy.java:272)
	at java.lang.Thread.run(Thread.java:748)
13:01:40.699 [SauceLabs addTestToDashboard seleniumSessionId [0010cfc780df49a8a3d71f4fce68ca7f] testCompleted [true]] ERROR d.z.e.z.p.CloudTestingRemoteProxy - java.lang.NullPointerException
java.lang.NullPointerException: null
	at de.zalando.ep.zalenium.proxy.SauceLabsRemoteProxy.getTestInformation(SauceLabsRemoteProxy.java:107)
	at de.zalando.ep.zalenium.proxy.CloudTestingRemoteProxy.lambda$0(CloudTestingRemoteProxy.java:272)
	at java.lang.Thread.run(Thread.java:748)
-- LOG 13:01:40:747761602 WaitForVideosTransferred succeeded for a total of 3

**Comment by romainlouvet** [comment]
https://github.com/zalando/zalenium/blob/4d27dde9cf04e95fa49f4bc7e5d0b781af7761de/src/main/java/de/zalando/ep/zalenium/proxy/SauceLabsRemoteProxy.java#L23 
 in EU -> https://eu-central-1.saucelabs.com/rest/v1 @diemol

**Comment by diemol** [comment]
We need to change that, reopening.
