### ISSUE TITLE
Unable to create remote chrome session when 'name' capability is provided

### ISSUE THREAD

**Issue by mcopjan** [zalando/zalenium#972]
Hi,
I am trying to spin up a new remote Chrome session in Zalenium. Provided example from Zalenium documentation suggests to use DesiredCapabilitites as follows

    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.FIREFOX);
    desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.LINUX);
    desiredCapabilities.setCapability("name", "myTestName");

Since DesiredCapabilities are deprecated in my version of Selenium (3.141.0) I would like to ask what is the suggested approach when using DriverOptions? When using the following code:

    var ChromeOptions = new ChromeOptions();
    ChromeOptions.AddArguments(new List<string>(){"start-maximized", "disable-infobars"});
    ChromeOptions.AddAdditionalCapability("name", "myTestName");
    var driver = new RemoteWebDriver(configuration.RemoteAddress, ChromeOptions);

**Fails with** 
``
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to create session from {
  "desiredCapabilities": {
    "browserName": "chrome",
    "server:CONFIG_UUID": "8e361545-6672-4d56-86eb-56ef6bf3197d",
    "goog:chromeOptions": {
      "args": [
        "start-maximized",
        "disable-infobars"
      ],
      "name": "myTestName"
    }
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "args": [
            "start-maximized",
            "disable-infobars"
          ],
          "name": "myTestName"
        },
        "server:CONFIG_UUID": "8e361545-6672-4d56-86eb-56ef6bf3197d"
      }
    ]
  }
}
Build info: version: '3.141.59', revision: '82b03c358b', time: '2019-04-30T22:04:50'
System info: host: '7e3989e1c90f', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.125-linuxkit', java.version: '1.8.0_191'
Driver info: driver.version: unknown (SessionNotCreated)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at UI.Framework.Clients.ChromeRemote..ctor(IFrameworkConfiguration configuration, ITestContext testContext, Dictionary`2 capabilities) in C:\Users\martinco\Documents\ui-test-with-framework\UI Framework\Clients\ChromeRemote.cs:line 65
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
   at Ninject.ResolutionExtensions.Get[T](IResolutionRoot root, IParameter[] parameters)
   at UI.Framework.DI.ClientActivator.Activate(Dictionary`2 capabilities) in C:\Users\martinco\Documents\ui-test-with-framework\UI Framework\DI\ClientActivator.cs:line 18
   at UI.Tests.Core.ActivateClient(Dictionary`2 desiredCapabilities) in C:\Users\martinco\Documents\ui-test-with-framework\UI Tests\Core.cs:line 14
   at UI.Tests.Core.ActivateClient(Uri uri, Dictionary`2 desiredCapabilities) in C:\Users\martinco\Documents\ui-test-with-framework\UI Tests\Core.cs:line 19
   at UI.Tests.Test.TestClientActivation() in C:\Users\martinco\Documents\ui-test-with-framework\UI Tests\Test.cs:line 18
``

I am not having any problems when omitting the "name" capability.
Please advise

**Comment by diemol** [comment]
@mcopjan 
Non standard capabilities need to be prefixed, in this case it should be `zal:name`. I think we need to update the docs to reflect that.

**Comment by mcopjan** [comment]
@diemol thanks for your quick response.

Unfortunately using ChromeOptions.AddAdditionalCapability("zal:name", "myTestName") does not resolve the problem.
``
System.InvalidOperationException : Unable to create session from {
  "desiredCapabilities": {
    "browserName": "chrome",
    "server:CONFIG_UUID": "2b4e195f-4f42-409c-ab9c-a9431b50e08d",
    "goog:chromeOptions": {
      "args": [
        "start-maximized",
        "disable-infobars"
      ],
      "zal:name": "myTestName"
    }
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "args": [
            "start-maximized",
            "disable-infobars"
          ],
          "zal:name": "myTestName"
        },
        "server:CONFIG_UUID": "2b4e195f-4f42-409c-ab9c-a9431b50e08d"
      }
    ]
  }
}
Build info: version: '3.141.59', revision: '82b03c358b', time: '2019-04-30T22:04:50'
System info: host: 'fbc13ff85659', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.125-linuxkit', java.version: '1.8.0_191'
Driver info: driver.version: unknown (SessionNotCreated)
TearDown : System.InvalidOperationException : Unable to create session from {
  "desiredCapabilities": {
    "browserName": "chrome",
    "server:CONFIG_UUID": "1f9a4be2-24eb-47d0-ba32-1382078b8942",
    "goog:chromeOptions": {
      "args": [
        "start-maximized",
        "disable-infobars"
      ],
      "zal:name": "myTestName"
    }
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "args": [
            "start-maximized",
            "disable-infobars"
          ],
          "zal:name": "myTestName"
        },
        "server:CONFIG_UUID": "1f9a4be2-24eb-47d0-ba32-1382078b8942"
      }
    ]
  }
}
Build info: version: '3.141.59', revision: '82b03c358b', time: '2019-04-30T22:04:50'
System info: host: '3937b14276cf', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.125-linuxkit', java.version: '1.8.0_191'
Driver info: driver.version: unknown (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at UI.Framework.Clients.ChromeRemote..ctor(IFrameworkConfiguration configuration, ITestContext testContext, Dictionary`2 capabilities) in C:\Users\martinco\Documents\ui-test-with-framework\UI Framework\Clients\ChromeRemote.cs:line 29
   at DynamicInjector00b756fbc72646aaa7b27e13a28c0889(Object[] )
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
   at Ninject.ResolutionExtensions.Get[T](IResolutionRoot root, IParameter[] parameters)
   at UI.Framework.DI.ClientActivator.Activate(Dictionary`2 capabilities) in C:\Users\martinco\Documents\ui-test-with-framework\UI Framework\DI\ClientActivator.cs:line 18
   at UI.Tests.Core.ActivateClient(Dictionary`2 desiredCapabilities) in C:\Users\martinco\Documents\ui-test-with-framework\UI Tests\Core.cs:line 14
   at UI.Tests.Core.ActivateClient(Uri uri, Dictionary`2 desiredCapabilities) in C:\Users\martinco\Documents\ui-test-with-framework\UI Tests\Core.cs:line 19
   at UI.Tests.Test.TestClientActivation() in C:\Users\martinco\Documents\ui-test-with-framework\UI Tests\Test.cs:line 18
--TearDown
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at UI.Framework.Clients.ChromeRemote..ctor(IFrameworkConfiguration configuration, ITestContext testContext, Dictionary`2 capabilities) in C:\Users\martinco\Documents\ui-test-with-framework\UI Framework\Clients\ChromeRemote.cs:line 29
   at DynamicInjector00b756fbc72646aaa7b27e13a28c0889(Object[] )
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
   at Ninject.ResolutionExtensions.Get[T](IResolutionRoot root, IParameter[] parameters)
   at UI.Tests.Core.get_Client() in C:\Users\martinco\Documents\ui-test-with-framework\UI Tests\Core.cs:line 23
   at UI.Tests.Test.TearDown() in C:\Users\martinco\Documents\ui-test-with-framework\UI Tests\Test.cs:line 44
``

**Comment by diemol** [comment]
Ah, you need to do:

```
ChromeOptions.AddAdditionalCapability("zal:name", "myTestName", true);
```

The `true` value marks this capability as global, because what is happening right now is that `zal:name` is ending up inside `goog:chromeOptions`.

**Comment by mcopjan** [comment]
@diemol legend!  thanks that works.
